// Generated by Claude Opus 4.8 (claude.ai/code) · 2026-09-15
namespace Airudit.MdBook.UnitTests;

using Airudit.MdBook.Core;
using Markdig;

/// <summary>
/// Build-time diagram rendering (issue #5), exercised through the public API with a stubbed provider —
/// no Docker and no network. Covers fence routing, the SVG inlining, the template colour-scheme
/// reader, provider tag sets, and the unrendered-diagram fallback + warning.
/// </summary>
public class DiagramRenderingTests
{
    // --- rendering pipeline (stub provider) ---

    [Fact]
    public void A_recognised_diagram_fence_is_replaced_by_inline_svg()
    {
        var svg = "<?xml version=\"1.0\"?>\n<!DOCTYPE svg>\n<svg id=\"d\"><g/></svg>\n";
        var html = Render("```mermaid\nA-->B\n```", new StubProvider("mermaid", svg));

        Assert.Contains("<figure class=\"diagram\">", html);
        Assert.Contains("<svg id=\"d\">", html);
        Assert.DoesNotContain("<?xml", html);          // prolog stripped
        Assert.DoesNotContain("<!DOCTYPE", html);       // doctype stripped
        Assert.DoesNotContain("language-mermaid", html); // not left as a plain code block
    }

    [Fact]
    public void The_active_color_scheme_is_passed_to_the_provider()
    {
        DiagramColorScheme? seen = null;
        var provider = new StubProvider("mermaid", "<svg/>", s => seen = s);

        Render("```mermaid\nA-->B\n```", provider, scheme: DiagramColorScheme.Dark);

        Assert.Equal(DiagramColorScheme.Dark, seen);
    }

    [Fact]
    public void An_unrendered_diagram_falls_back_to_plain_and_is_noted()
    {
        var sink = new DiagramWarningSink();
        // Provider that cannot render mermaid (only knows plantuml): the fence must stay plain.
        var html = Render("```mermaid\nA-->B\n```", new StubProvider("plantuml", "<svg/>"), sink);

        Assert.DoesNotContain("<figure", html);
        Assert.Contains("language-mermaid", html); // plain fenced code preserved, source visible
        Assert.True(sink.Any);
        Assert.Contains("mermaid", sink.SkippedTags);
    }

    [Fact]
    public void A_non_diagram_fence_is_left_untouched_and_not_noted()
    {
        var sink = new DiagramWarningSink();
        var html = Render("```csharp\nvar x = 1;\n```", new StubProvider("mermaid", "<svg/>"), sink);

        Assert.DoesNotContain("<figure", html);
        Assert.Contains("language-csharp", html);
        Assert.False(sink.Any);
    }

    // --- SvgInliner ---

    [Fact]
    public void SvgInliner_strips_the_prolog_and_wraps_the_element()
    {
        var wrapped = SvgInliner.Wrap("<?xml version=\"1.0\"?>\n<svg id=\"x\"><g/></svg>\n");

        Assert.StartsWith("<figure class=\"diagram\">", wrapped);
        Assert.Contains("<svg id=\"x\">", wrapped);
        Assert.Contains("</figure>", wrapped);
        Assert.DoesNotContain("<?xml", wrapped);
    }

    // --- TemplateColorScheme: the standard <meta name="color-scheme"> tag ---

    [Theory]
    [InlineData("<meta name=\"color-scheme\" content=\"dark\">", DiagramColorScheme.Dark)]
    [InlineData("<meta name=\"color-scheme\" content=\"light\">", DiagramColorScheme.Light)]
    [InlineData("<meta name='color-scheme' content='dark light'>", DiagramColorScheme.Dark)]   // list order wins
    [InlineData("<meta content=\"light dark\" name=\"color-scheme\">", DiagramColorScheme.Light)] // attr order-agnostic
    [InlineData("<meta name=\"color-scheme\" content=\"only dark\">", DiagramColorScheme.Dark)]  // "only" ignored
    [InlineData("<html><head><title>x</title></head></html>", DiagramColorScheme.Light)]        // absent -> light
    public void TemplateColorScheme_reads_the_standard_meta_tag(string html, DiagramColorScheme expected)
    {
        Assert.Equal(expected, TemplateColorScheme.Resolve(html));
    }

    // --- provider tag sets and configuration ---

    [Fact]
    public void Docker_provider_recognises_its_registered_tags()
    {
        var provider = new DockerDiagramProvider();

        Assert.True(provider.CanRender("mermaid"));
        Assert.True(provider.CanRender("plantuml"));
        Assert.True(provider.CanRender("PUML")); // case-insensitive
        Assert.False(provider.CanRender("graphviz"));
        Assert.False(provider.CanRender(""));
    }

    [Fact]
    public void Kroki_provider_recognises_kroki_types_and_needs_a_url()
    {
        var provider = new KrokiDiagramProvider("https://kroki.io/");
        Assert.True(provider.CanRender("mermaid"));
        Assert.True(provider.CanRender("graphviz"));
        Assert.False(provider.CanRender("not-a-diagram"));

        Assert.Throws<ArgumentException>(() => new KrokiDiagramProvider(""));
        Assert.Throws<ArgumentException>(() => new KrokiDiagramProvider("   "));
    }

    [Fact]
    public void Factory_maps_each_kind_to_a_provider()
    {
        Assert.False(DiagramProviderFactory.Create(DiagramProviderKind.None, null).CanRender("mermaid"));
        Assert.True(DiagramProviderFactory.Create(DiagramProviderKind.Docker, null).CanRender("mermaid"));
        Assert.True(DiagramProviderFactory.Create(DiagramProviderKind.Kroki, "https://kroki.io/").CanRender("graphviz"));
    }

    // --- warning sink ---

    [Fact]
    public void Warning_sink_deduplicates_tags_case_insensitively()
    {
        var sink = new DiagramWarningSink();
        Assert.False(sink.Any);

        sink.NoteSkipped("mermaid");
        sink.NoteSkipped("MERMAID");
        sink.NoteSkipped("plantuml");

        Assert.True(sink.Any);
        Assert.Equal(2, sink.SkippedTags.Count);
    }

    // --- helpers ---

    private static string Render(string markdown, IDiagramProvider provider, DiagramWarningSink? sink = null, DiagramColorScheme scheme = DiagramColorScheme.Light)
    {
        sink ??= new DiagramWarningSink();
        var builder = new MarkdownPipelineBuilder();
        builder.Extensions.Add(new DiagramRenderingExtension(provider, scheme, sink));
        return Markdown.ToHtml(markdown, builder.Build());
    }

    private sealed class StubProvider : IDiagramProvider
    {
        private readonly string tag;
        private readonly string? svg;
        private readonly Action<DiagramColorScheme>? onRender;

        public StubProvider(string tag, string? svg, Action<DiagramColorScheme>? onRender = null)
        {
            this.tag = tag;
            this.svg = svg;
            this.onRender = onRender;
        }

        public bool CanRender(string diagramTag)
        {
            return string.Equals(diagramTag, this.tag, StringComparison.OrdinalIgnoreCase);
        }

        public bool TryRenderSvg(string diagramTag, string source, DiagramColorScheme scheme, out string svg)
        {
            this.onRender?.Invoke(scheme);
            if (this.CanRender(diagramTag) && this.svg != null)
            {
                svg = this.svg;
                return true;
            }

            svg = string.Empty;
            return false;
        }
    }
}
