// Generated by Claude Opus 4.8 (claude.ai/code) · 2026-09-15
namespace Airudit.MdBook.UnitTests;

using Airudit.MdBook.Core;
using Markdig;

/// <summary>
/// Build-time diagram rendering (issue #5), exercised through the public API with a stubbed provider —
/// no Docker and no network. Covers the async pre-render pass, the SVG inlining, fence routing, the
/// template colour-scheme reader, provider tag sets, and the unrendered-diagram fallback + warning.
/// </summary>
public class DiagramRenderingTests
{
    // --- pre-render + render pipeline (stub provider) ---

    [Fact]
    public async Task A_recognised_diagram_fence_is_replaced_by_inline_svg()
    {
        var svg = "<?xml version=\"1.0\"?>\n<!DOCTYPE svg>\n<svg id=\"d\"><g/></svg>\n";
        var html = await RenderAsync("```mermaid\nA-->B\n```", new StubProvider("mermaid", svg));

        Assert.Contains("<figure class=\"diagram\">", html);
        Assert.Contains("<svg id=\"d\">", html);
        Assert.DoesNotContain("<?xml", html);          // prolog stripped
        Assert.DoesNotContain("<!DOCTYPE", html);       // doctype stripped
        Assert.DoesNotContain("language-mermaid", html); // not left as a plain code block
    }

    [Fact]
    public async Task The_active_color_scheme_is_passed_to_the_provider()
    {
        DiagramColorScheme? seen = null;
        var provider = new StubProvider("mermaid", "<svg/>", s => seen = s);

        await RenderAsync("```mermaid\nA-->B\n```", provider, scheme: DiagramColorScheme.Dark);

        Assert.Equal(DiagramColorScheme.Dark, seen);
    }

    [Fact]
    public async Task An_unrendered_diagram_falls_back_to_plain_and_is_noted()
    {
        var sink = new DiagramWarningSink();
        // Provider that cannot render mermaid (only knows plantuml): the fence must stay plain.
        var html = await RenderAsync("```mermaid\nA-->B\n```", new StubProvider("plantuml", "<svg/>"), sink);

        Assert.DoesNotContain("<figure", html);
        Assert.Contains("language-mermaid", html); // plain fenced code preserved, source visible
        Assert.True(sink.Any);
        Assert.Contains("mermaid", sink.SkippedTags);
    }

    [Fact]
    public async Task A_non_diagram_fence_is_left_untouched_and_not_noted()
    {
        var sink = new DiagramWarningSink();
        var html = await RenderAsync("```csharp\nvar x = 1;\n```", new StubProvider("mermaid", "<svg/>"), sink);

        Assert.DoesNotContain("<figure", html);
        Assert.Contains("language-csharp", html);
        Assert.False(sink.Any);
    }

    [Fact]
    public async Task An_identical_diagram_is_rendered_once_and_reused()
    {
        var provider = new StubProvider("mermaid", "<svg id=\"x\"/>");
        var html = await RenderAsync("```mermaid\nA-->B\n```\n\ntext\n\n```mermaid\nA-->B\n```", provider);

        Assert.Equal(2, Occurrences(html, "<figure class=\"diagram\">")); // both fences rendered
        Assert.Equal(1, provider.RenderCount);                            // but the provider ran once
    }

    // --- SvgInliner ---

    [Fact]
    public void SvgInliner_strips_the_prolog_and_wraps_the_element()
    {
        var wrapped = SvgInliner.Wrap("<?xml version=\"1.0\"?>\n<svg id=\"x\"><g/></svg>\n");

        Assert.StartsWith("<figure class=\"diagram\">", wrapped);
        Assert.Contains("<svg id=\"x\">", wrapped);
        Assert.Contains("</figure>", wrapped);
        Assert.DoesNotContain("<?xml", wrapped);
    }

    // --- TemplateColorScheme: the standard <meta name="color-scheme"> tag ---

    [Theory]
    [InlineData("<meta name=\"color-scheme\" content=\"dark\">", DiagramColorScheme.Dark)]
    [InlineData("<meta name=\"color-scheme\" content=\"light\">", DiagramColorScheme.Light)]
    [InlineData("<meta name='color-scheme' content='dark light'>", DiagramColorScheme.Dark)]   // list order wins
    [InlineData("<meta content=\"light dark\" name=\"color-scheme\">", DiagramColorScheme.Light)] // attr order-agnostic
    [InlineData("<meta name=\"color-scheme\" content=\"only dark\">", DiagramColorScheme.Dark)]  // "only" ignored
    [InlineData("<html><head><title>x</title></head></html>", DiagramColorScheme.Light)]        // absent -> light
    public void TemplateColorScheme_reads_the_standard_meta_tag(string html, DiagramColorScheme expected)
    {
        Assert.Equal(expected, TemplateColorScheme.Resolve(html));
    }

    // --- provider tag sets and configuration ---

    [Fact]
    public void Docker_provider_recognises_its_registered_tags()
    {
        var provider = new DockerDiagramProvider();

        Assert.True(provider.CanRender("mermaid"));
        Assert.True(provider.CanRender("plantuml"));
        Assert.True(provider.CanRender("PUML")); // case-insensitive
        Assert.False(provider.CanRender("graphviz"));
        Assert.False(provider.CanRender(""));
    }

    [Fact]
    public void Kroki_provider_recognises_kroki_types_and_needs_a_url()
    {
        var provider = new KrokiDiagramProvider("https://kroki.io/");
        Assert.True(provider.CanRender("mermaid"));
        Assert.True(provider.CanRender("graphviz"));
        Assert.False(provider.CanRender("not-a-diagram"));

        Assert.Throws<ArgumentException>(() => new KrokiDiagramProvider(""));
        Assert.Throws<ArgumentException>(() => new KrokiDiagramProvider("   "));
    }

    [Fact]
    public void Factory_maps_each_kind_to_a_provider()
    {
        Assert.False(DiagramProviderFactory.Create(DiagramProviderKind.None, null).CanRender("mermaid"));
        Assert.True(DiagramProviderFactory.Create(DiagramProviderKind.Docker, null).CanRender("mermaid"));
        Assert.True(DiagramProviderFactory.Create(DiagramProviderKind.Kroki, "https://kroki.io/").CanRender("graphviz"));
    }

    // --- warning sink ---

    [Fact]
    public void Warning_sink_deduplicates_tags_case_insensitively()
    {
        var sink = new DiagramWarningSink();
        Assert.False(sink.Any);

        sink.NoteSkipped("mermaid");
        sink.NoteSkipped("MERMAID");
        sink.NoteSkipped("plantuml");

        Assert.True(sink.Any);
        Assert.Equal(2, sink.SkippedTags.Count);
    }

    // --- helpers ---

    // Mirrors the real flow: parse, run the async pre-render pass into a cache, then render
    // synchronously through the cache-reading extension.
    private static async Task<string> RenderAsync(string markdown, IDiagramProvider provider, DiagramWarningSink? sink = null, DiagramColorScheme scheme = DiagramColorScheme.Light)
    {
        sink ??= new DiagramWarningSink();
        var cache = new Dictionary<string, string?>(StringComparer.Ordinal);

        var document = Markdown.Parse(markdown);
        await DiagramPrerenderer.RenderAsync(document, provider, scheme, cache, sink);

        var builder = new MarkdownPipelineBuilder();
        builder.Extensions.Add(new DiagramRenderingExtension(cache));
        return Markdown.ToHtml(markdown, builder.Build());
    }

    private static int Occurrences(string haystack, string needle)
    {
        var count = 0;
        for (var i = haystack.IndexOf(needle, StringComparison.Ordinal); i >= 0; i = haystack.IndexOf(needle, i + needle.Length, StringComparison.Ordinal))
        {
            count++;
        }

        return count;
    }

    private sealed class StubProvider : IDiagramProvider
    {
        private readonly string tag;
        private readonly string? svg;
        private readonly Action<DiagramColorScheme>? onRender;
        private int renderCount;

        public StubProvider(string tag, string? svg, Action<DiagramColorScheme>? onRender = null)
        {
            this.tag = tag;
            this.svg = svg;
            this.onRender = onRender;
        }

        public int RenderCount => this.renderCount;

        public bool CanRender(string diagramTag)
        {
            return string.Equals(diagramTag, this.tag, StringComparison.OrdinalIgnoreCase);
        }

        public Task<string?> RenderSvgAsync(string diagramTag, string source, DiagramColorScheme scheme, CancellationToken cancellationToken)
        {
            Interlocked.Increment(ref this.renderCount);
            this.onRender?.Invoke(scheme);
            return Task.FromResult(this.CanRender(diagramTag) && this.svg != null ? this.svg : null);
        }
    }
}
