// Generated by Claude Opus 4.8 (claude.ai/code) · 2026-09-24
namespace Airudit.MdBook.UnitTests;

using Airudit.MdBook.Core;

/// <summary>
/// The doc manifest parsed from a <c>.mdbook</c> file's front-matter (issue #30):
/// <see cref="DocManifest.FromFrontMatter"/> field mapping and defaults.
/// </summary>
public class DocManifestTests
{
    private static DocManifest From(string frontMatter) => DocManifest.FromFrontMatter(FrontMatter.Parse(frontMatter));

    [Fact]
    public void All_fields_are_read()
    {
        var manifest = From(
            "priority: [readme, install/prereqs]\n" +
            "exclude: [PromethaiApi/, beta.md]\n" +
            "exclusive: yes\n" +
            "toc: no\n" +
            "priority-title: Read these first\n" +
            "toc-title: In this book");

        Assert.Equal(new[] { "readme", "install/prereqs" }, manifest.Priority);
        Assert.Equal(new[] { "PromethaiApi/", "beta.md" }, manifest.Exclude);
        Assert.True(manifest.Exclusive);
        Assert.False(manifest.Toc);
        Assert.Equal("Read these first", manifest.PriorityTitle);
        Assert.Equal("In this book", manifest.TocTitle);
    }

    [Fact]
    public void An_empty_manifest_uses_defaults()
    {
        var manifest = From("title: Book\nlang: en");

        Assert.Empty(manifest.Priority);
        Assert.Empty(manifest.Exclude);
        Assert.False(manifest.Exclusive);
        Assert.True(manifest.Toc);
        Assert.Null(manifest.PriorityTitle);
        Assert.Null(manifest.TocTitle);
    }

    [Fact]
    public void Toc_defaults_to_true_and_is_only_turned_off_explicitly()
    {
        Assert.True(From("title: Book").Toc);
        Assert.False(From("toc: no").Toc);
        Assert.True(From("toc: yes").Toc);
    }

    [Fact]
    public void Exclusive_defaults_to_false()
    {
        Assert.False(From("title: Book").Exclusive);
        Assert.True(From("exclusive: yes").Exclusive);
    }

    [Fact]
    public void A_block_style_exclude_list_is_read()
    {
        var manifest = From("exclude:\n  - PromethaiApi/\n  - advanced/*.md");
        Assert.Equal(new[] { "PromethaiApi/", "advanced/*.md" }, manifest.Exclude);
    }
}
