// Generated by Claude Opus 4.8 (claude.ai/code) · 2026-09-24
namespace Airudit.MdBook.UnitTests;

using Airudit.MdBook.Core;
using Markdig;
using Markdig.Syntax;

/// <summary>
/// The house YAML front-matter reader <see cref="FrontMatter"/>: scalars, flow and block
/// sequences, booleans, integers, quoting and comments (issues #29, #30).
/// </summary>
public class FrontMatterTests
{
    private static FrontMatter Parse(string text) => FrontMatter.Parse(text);

    // --- scalars ---

    [Fact]
    public void A_scalar_value_is_read()
    {
        Assert.Equal("Hello", Parse("title: Hello").GetString("title"));
    }

    [Fact]
    public void A_missing_key_is_null()
    {
        Assert.Null(Parse("title: Hello").GetString("lang"));
    }

    [Fact]
    public void An_empty_scalar_is_null()
    {
        Assert.Null(Parse("title:").GetString("title"));
    }

    [Fact]
    public void A_double_quoted_scalar_is_unquoted_and_keeps_its_colon()
    {
        Assert.Equal("Hello: World", Parse("title: \"Hello: World\"").GetString("title"));
    }

    [Fact]
    public void A_single_quoted_scalar_is_unquoted()
    {
        Assert.Equal("Hello", Parse("title: 'Hello'").GetString("title"));
    }

    [Fact]
    public void An_inline_comment_is_stripped_from_a_scalar()
    {
        Assert.Equal("en", Parse("lang: en # the language").GetString("lang"));
    }

    [Fact]
    public void A_hash_without_leading_space_stays_part_of_the_value()
    {
        Assert.Equal("issue#30", Parse("ref: issue#30").GetString("ref"));
    }

    [Fact]
    public void A_full_line_comment_is_ignored()
    {
        Assert.Equal("Hello", Parse("# a comment\ntitle: Hello").GetString("title"));
    }

    // --- flow sequences ---

    [Fact]
    public void A_flow_list_is_split_into_items()
    {
        Assert.Equal(new[] { "a", "b", "c" }, Parse("priority: [a, b, c]").GetList("priority"));
    }

    [Fact]
    public void A_flow_list_trims_spaces_and_unquotes_items()
    {
        Assert.Equal(new[] { "a b", "c" }, Parse("priority: [ \"a b\", c ]").GetList("priority"));
    }

    [Fact]
    public void An_empty_flow_list_yields_no_items()
    {
        Assert.Empty(Parse("priority: []").GetList("priority"));
    }

    // --- block sequences ---

    [Fact]
    public void An_indented_block_list_is_read()
    {
        Assert.Equal(new[] { "a", "b" }, Parse("exclude:\n  - a\n  - b").GetList("exclude"));
    }

    [Fact]
    public void A_column_zero_block_list_is_read()
    {
        Assert.Equal(new[] { "a", "b" }, Parse("exclude:\n- a\n- b").GetList("exclude"));
    }

    [Fact]
    public void A_block_list_stops_at_the_next_key()
    {
        var fm = Parse("exclude:\n  - a\n  - b\ntitle: Book");
        Assert.Equal(new[] { "a", "b" }, fm.GetList("exclude"));
        Assert.Equal("Book", fm.GetString("title"));
    }

    [Fact]
    public void A_block_list_item_keeps_a_path_with_a_trailing_slash()
    {
        Assert.Equal(new[] { "PromethaiApi/", "advanced/*.md" }, Parse("exclude:\n  - PromethaiApi/\n  - advanced/*.md").GetList("exclude"));
    }

    [Fact]
    public void A_missing_list_is_empty_not_null()
    {
        Assert.Empty(Parse("title: Book").GetList("priority"));
    }

    [Fact]
    public void A_scalar_read_as_a_list_yields_one_item()
    {
        Assert.Equal(new[] { "only.md" }, Parse("exclude: only.md").GetList("exclude"));
    }

    // --- booleans ---

    [Theory]
    [InlineData("yes", true)]
    [InlineData("no", false)]
    [InlineData("true", true)]
    [InlineData("false", false)]
    [InlineData("on", true)]
    [InlineData("off", false)]
    [InlineData("1", true)]
    [InlineData("0", false)]
    public void A_boolean_scalar_is_parsed(string value, bool expected)
    {
        Assert.Equal(expected, Parse("toc: " + value).GetBool("toc"));
    }

    [Fact]
    public void An_unrecognised_boolean_is_null()
    {
        Assert.Null(Parse("toc: maybe").GetBool("toc"));
    }

    [Fact]
    public void A_missing_boolean_is_null()
    {
        Assert.Null(Parse("title: Book").GetBool("toc"));
    }

    // --- integers ---

    [Fact]
    public void An_integer_scalar_is_parsed()
    {
        Assert.Equal(1002, Parse("order: 1002").GetInt("order"));
    }

    [Fact]
    public void A_non_integer_is_null()
    {
        Assert.Null(Parse("order: soon").GetInt("order"));
    }

    [Fact]
    public void A_missing_integer_is_null()
    {
        Assert.Null(Parse("title: Book").GetInt("order"));
    }

    // --- empties and documents ---

    [Fact]
    public void Empty_text_has_no_keys()
    {
        Assert.Null(Parse(string.Empty).GetString("title"));
    }

    [Fact]
    public void A_stray_fence_line_is_tolerated()
    {
        Assert.Equal("Book", Parse("---\ntitle: Book\n---").GetString("title"));
    }

    [Fact]
    public void A_document_without_front_matter_reads_as_empty()
    {
        var dom = Markdown.Parse("# Just a heading\n\nBody.", BuildPipeline());
        Assert.Null(FrontMatter.FromDocument(dom).GetString("title"));
    }

    [Fact]
    public void A_documents_front_matter_block_is_read()
    {
        var dom = Markdown.Parse("---\ntitle: From Doc\npriority: [a, b]\n---\n\n# Heading", BuildPipeline());
        var fm = FrontMatter.FromDocument(dom);
        Assert.Equal("From Doc", fm.GetString("title"));
        Assert.Equal(new[] { "a", "b" }, fm.GetList("priority"));
    }

    private static MarkdownPipeline BuildPipeline()
    {
        return new MarkdownPipelineBuilder().UseYamlFrontMatter().Build();
    }
}
