// Generated by Claude Opus 4.8 (claude.ai/code) · 2026-09-24
namespace Airudit.MdBook.UnitTests;

using Airudit.MdBook.Core;

/// <summary>
/// Path matching for doc-manifest <c>exclude</c> / <c>priority</c> entries
/// (<see cref="ManifestMatcher"/>): directories, globs, and the optional language/extension
/// rule (issue #30).
/// </summary>
public class ManifestMatcherTests
{
    // --- plain file paths, extension and language optional ---

    [Theory]
    [InlineData("beta.md", "beta.md", true)]
    [InlineData("beta", "beta.md", true)]
    [InlineData("beta.md", "beta", true)]
    [InlineData("beta", "beta2.md", false)]
    [InlineData("guide/intro", "guide/intro.md", true)]
    [InlineData("guide/intro", "guide/intro.en-US.md", true)]
    [InlineData("guide/intro", "guide/intro.en.md", true)]
    [InlineData("guide/intro.en-US", "guide/intro.en-US.md", true)]
    [InlineData("intro", "guide/intro.md", false)]
    public void A_plain_entry_matches_with_extension_and_language_optional(string entry, string relativePath, bool expected)
    {
        Assert.Equal(expected, ManifestMatcher.Matches(entry, relativePath));
    }

    [Fact]
    public void Matching_is_case_insensitive()
    {
        Assert.True(ManifestMatcher.Matches("ReadMe", "readme.md"));
    }

    // --- directories (trailing slash) ---

    [Theory]
    [InlineData("PromethaiApi/", "PromethaiApi/index.md", true)]
    [InlineData("PromethaiApi/", "PromethaiApi/sub/deep.md", true)]
    [InlineData("PromethaiApi/", "PromethaiApiExtra/x.md", false)]
    [InlineData("PromethaiApi/", "Other/x.md", false)]
    public void A_directory_entry_matches_its_whole_subtree(string entry, string relativePath, bool expected)
    {
        Assert.Equal(expected, ManifestMatcher.Matches(entry, relativePath));
    }

    // --- globs (a single segment, not crossing '/') ---

    [Theory]
    [InlineData("advanced/*.md", "advanced/x.md", true)]
    [InlineData("advanced/*.md", "advanced/y.md", true)]
    [InlineData("advanced/*.md", "advanced/sub/z.md", false)]
    [InlineData("advanced/*.md", "basic/x.md", false)]
    [InlineData("*.md", "top.md", true)]
    [InlineData("*.md", "dir/nested.md", false)]
    public void A_glob_matches_within_one_segment(string entry, string relativePath, bool expected)
    {
        Assert.Equal(expected, ManifestMatcher.Matches(entry, relativePath));
    }

    // --- edges ---

    [Fact]
    public void An_empty_entry_or_path_never_matches()
    {
        Assert.False(ManifestMatcher.Matches(string.Empty, "a.md"));
        Assert.False(ManifestMatcher.Matches("a.md", string.Empty));
    }

    [Fact]
    public void Backslash_paths_are_normalised()
    {
        Assert.True(ManifestMatcher.Matches("guide/intro", "guide\\intro.md"));
    }
}
