// Generated by Claude Opus 4.8 (claude.ai/code) · 2026-09-07
namespace Airudit.MdBook.UnitTests;

using Airudit.MdBook.Core;
using System.Text;

/// <summary>
/// Output-destination behaviour (issue #9): the in-place side-by-side HTML files, the
/// <c>--single-file</c> bundle and the <c>--export</c> copies, and how <c>--side</c> gates them.
/// </summary>
public class OutputModeTests
{
    // --- --side flag logic, exercised through the real CLI parse task ---

    [Fact]
    public void Side_by_side_is_on_by_default_with_no_output_destination()
    {
        using var dir = new TempTree(("doc.md", "# Hi"));
        var layer = ParseArgs(dir.Root);
        Assert.True(layer.SideBySide);
    }

    [Fact]
    public void Single_file_suppresses_side_by_side()
    {
        using var dir = new TempTree(("doc.md", "# Hi"));
        var layer = ParseArgs(dir.Root, "--single-file", Path.Combine(dir.Root, "all.html"));
        Assert.False(layer.SideBySide);
    }

    [Fact]
    public void Export_suppresses_side_by_side()
    {
        using var dir = new TempTree(("doc.md", "# Hi"));
        var layer = ParseArgs(dir.Root, "--export", Path.Combine(dir.Root, "out"));
        Assert.False(layer.SideBySide);
    }

    [Fact]
    public void Side_flag_forces_side_by_side_alongside_single_file()
    {
        using var dir = new TempTree(("doc.md", "# Hi"));
        var layer = ParseArgs(dir.Root, "--single-file", Path.Combine(dir.Root, "all.html"), "--side");
        Assert.True(layer.SideBySide);
    }

    [Fact]
    public void Side_flag_forces_side_by_side_alongside_export()
    {
        using var dir = new TempTree(("doc.md", "# Hi"));
        var layer = ParseArgs(dir.Root, "--export", Path.Combine(dir.Root, "out"), "--side");
        Assert.True(layer.SideBySide);
    }

    // --- suppression actually skips the in-place write, but still renders in memory ---

    [Fact]
    public void Suppressed_side_by_side_does_not_write_the_in_place_html()
    {
        using var dir = new TempTree(("doc.md", "# Hi"));
        var item = RenderSingleFile(dir, "doc.md", sideBySide: false);
        Assert.False(File.Exists(Path.Combine(dir.Root, "doc.md.html")));
        Assert.NotNull(item.RenderedPage);
    }

    [Fact]
    public void Enabled_side_by_side_writes_the_in_place_html()
    {
        using var dir = new TempTree(("doc.md", "# Hi"));
        RenderSingleFile(dir, "doc.md", sideBySide: true);
        Assert.True(File.Exists(Path.Combine(dir.Root, "doc.md.html")));
    }

    // --- the full pipeline: --single-file + --export with no --side ---

    [Fact]
    public void Export_and_single_file_write_outputs_but_no_in_place_files()
    {
        using var dir = new TempTree(
            ("help/README.md", "# Readme\n\n[b](b.md)"),
            ("help/b.md", "# Bee"));
        var single = Path.Combine(dir.Root, "all.html");
        var outDir = Path.Combine(dir.Root, "out");

        RunCli(Path.Combine(dir.Root, "help"), "--single-file", single, "--export", outDir);

        // single file written
        Assert.True(File.Exists(single));
        // export dir has the rendered pages, from memory
        Assert.True(File.Exists(Path.Combine(outDir, "help", "README.md.html")));
        Assert.True(File.Exists(Path.Combine(outDir, "help", "b.md.html")));
        // no in-place side-by-side files next to the sources
        Assert.False(File.Exists(Path.Combine(dir.Root, "help", "README.md.html")));
        Assert.False(File.Exists(Path.Combine(dir.Root, "help", "b.md.html")));
    }

    // Runs only the CLI parse task and returns the populated markdown layer.
    private static SimpleMarkdownToHtmlLayer ParseArgs(params string[] args)
    {
        var context = new PackageContext();
        context.AddLayer(new CommandLineLayer(new StringWriter(), new StringWriter(), new StringReader(string.Empty), args));
        var task = new CommandLineMarkdownToHtmlPrepareTask();
        task.Visit(context);
        return context.RequireSingleLayer<SimpleMarkdownToHtmlLayer>();
    }

    // Renders one source file through the real render task with a chosen SideBySide setting.
    private static SimpleMarkdownToHtmlLayerItem RenderSingleFile(TempTree dir, string relativePath, bool sideBySide)
    {
        var layer = new SimpleMarkdownToHtmlLayer();
        layer.SideBySide = sideBySide;
        var item = layer.AddFile(new FileInfo(Path.Combine(dir.Root, relativePath)), true);
        item.RelativePath = new[] { Path.GetFileName(relativePath) };

        var context = new PackageContext();
        context.AddLayer(layer);
        var task = new SimpleMarkdownToHtmlTask();
        task.Visit(context);
        task.Run(context);
        return item;
    }

    // Runs the whole task pipeline exactly as Program.cs does, with the built-in template.
    private static void RunCli(params string[] args)
    {
        var context = new PackageContext();
        context.AddLayer(new CommandLineLayer(new StringWriter(), new StringWriter(), new StringReader(string.Empty),
            args.Concat(new[] { "--template", "builtin:default.light.html" }).ToArray()));
        var tasks = new ITask[]
        {
            new CommandLineMarkdownToHtmlPrepareTask(),
            new SimpleMarkdownToHtmlTask(),
            new ExportMarkdownToHtmlTask(),
            new CombineMarkdownToHtmlTask(),
        };
        foreach (var task in tasks)
        {
            task.Visit(context);
        }

        foreach (var task in tasks)
        {
            task.Verify(context);
        }

        foreach (var task in tasks)
        {
            task.Run(context);
        }
    }

    // A throwaway directory tree of source files, removed on dispose.
    private sealed class TempTree : IDisposable
    {
        public TempTree(params (string Path, string Body)[] files)
        {
            this.Root = Path.Combine(Path.GetTempPath(), "mdbook-tests-" + Guid.NewGuid().ToString("N"));
            Directory.CreateDirectory(this.Root);
            foreach (var (relativePath, body) in files)
            {
                var full = Path.Combine(this.Root, relativePath);
                Directory.CreateDirectory(Path.GetDirectoryName(full)!);
                File.WriteAllText(full, body, Encoding.UTF8);
            }
        }

        public string Root { get; }

        public void Dispose()
        {
            try
            {
                Directory.Delete(this.Root, true);
            }
            catch (DirectoryNotFoundException)
            {
            }
        }
    }
}
