// Generated by Claude Opus 4.8 (claude.ai/code) · 2026-09-07
namespace Airudit.MdBook.UnitTests;

using Airudit.MdBook.Core;
using System.Text;

/// <summary>
/// Output-destination behaviour (issue #9): the in-place side-by-side HTML files, the
/// <c>--single-file</c> bundle and the <c>--export</c> copies, and how <c>--side</c> gates them.
/// </summary>
public class OutputModeTests
{
    // --- --side flag logic, exercised through the real CLI parse task ---

    [Fact]
    public void Side_by_side_is_on_by_default_with_no_output_destination()
    {
        using var dir = new TempTree(("doc.md", "# Hi"));
        var layer = ParseArgs(dir.Root);
        Assert.True(layer.SideBySide);
    }

    [Fact]
    public void Single_file_suppresses_side_by_side()
    {
        using var dir = new TempTree(("doc.md", "# Hi"));
        var layer = ParseArgs(dir.Root, "--single-file", Path.Combine(dir.Root, "all.html"));
        Assert.False(layer.SideBySide);
    }

    [Fact]
    public void Export_suppresses_side_by_side()
    {
        using var dir = new TempTree(("doc.md", "# Hi"));
        var layer = ParseArgs(dir.Root, "--export", Path.Combine(dir.Root, "out"));
        Assert.False(layer.SideBySide);
    }

    [Fact]
    public void Side_flag_forces_side_by_side_alongside_single_file()
    {
        using var dir = new TempTree(("doc.md", "# Hi"));
        var layer = ParseArgs(dir.Root, "--single-file", Path.Combine(dir.Root, "all.html"), "--side");
        Assert.True(layer.SideBySide);
    }

    [Fact]
    public void Side_flag_forces_side_by_side_alongside_export()
    {
        using var dir = new TempTree(("doc.md", "# Hi"));
        var layer = ParseArgs(dir.Root, "--export", Path.Combine(dir.Root, "out"), "--side");
        Assert.True(layer.SideBySide);
    }

    // --- suppression actually skips the in-place write, but still renders in memory ---

    [Fact]
    public void Suppressed_side_by_side_does_not_write_the_in_place_html()
    {
        using var dir = new TempTree(("doc.md", "# Hi"));
        var item = RenderSingleFile(dir, "doc.md", sideBySide: false);
        Assert.False(File.Exists(Path.Combine(dir.Root, "doc.md.html")));
        Assert.NotNull(item.RenderedPage);
    }

    [Fact]
    public void Enabled_side_by_side_writes_the_in_place_html()
    {
        using var dir = new TempTree(("doc.md", "# Hi"));
        RenderSingleFile(dir, "doc.md", sideBySide: true);
        Assert.True(File.Exists(Path.Combine(dir.Root, "doc.md.html")));
    }

    // --- the full pipeline: --single-file + --export with no --side ---

    [Fact]
    public void Export_and_single_file_write_outputs_but_no_in_place_files()
    {
        using var dir = new TempTree(
            ("help/README.md", "# Readme\n\n[b](b.md)"),
            ("help/b.md", "# Bee"));
        var single = Path.Combine(dir.Root, "all.html");
        var outDir = Path.Combine(dir.Root, "out");

        RunCli(Path.Combine(dir.Root, "help"), "--single-file", single, "--export", outDir);

        // single file written
        Assert.True(File.Exists(single));
        // export dir has the rendered pages, from memory
        Assert.True(File.Exists(Path.Combine(outDir, "help", "README.md.html")));
        Assert.True(File.Exists(Path.Combine(outDir, "help", "b.md.html")));
        // no in-place side-by-side files next to the sources
        Assert.False(File.Exists(Path.Combine(dir.Root, "help", "README.md.html")));
        Assert.False(File.Exists(Path.Combine(dir.Root, "help", "b.md.html")));
    }

    // --- issue #4: file ordering and de-duplication for the assembled output ---

    [Fact]
    public void Explicit_files_keep_their_command_line_order()
    {
        using var dir = new TempTree(("a.md", "# a"), ("b.md", "# b"));
        var names = ParseItemNames(Path.Combine(dir.Root, "b.md"), Path.Combine(dir.Root, "a.md"));
        Assert.Equal(new[] { "b.md", "a.md" }, names);
    }

    [Fact]
    public void Directory_files_are_sorted_alphabetically()
    {
        using var dir = new TempTree(("d/zeta.md", "#"), ("d/alpha.md", "#"), ("d/mid.md", "#"));
        var names = ParseItemNames(Path.Combine(dir.Root, "d"));
        Assert.Equal(new[] { "alpha.md", "mid.md", "zeta.md" }, names);
    }

    [Fact]
    public void Readme_then_index_are_hoisted_to_the_front_of_a_directory()
    {
        using var dir = new TempTree(("d/zeta.md", "#"), ("d/alpha.md", "#"), ("d/README.md", "#"), ("d/Index.md", "#"));
        var names = ParseItemNames(Path.Combine(dir.Root, "d"));
        Assert.Equal(new[] { "README.md", "Index.md", "alpha.md", "zeta.md" }, names);
    }

    [Fact]
    public void An_explicit_file_before_a_directory_keeps_its_position_and_is_not_duplicated()
    {
        using var dir = new TempTree(("help/alpha.md", "#"), ("help/zeta.md", "#"));
        var names = ParseItemNames(Path.Combine(dir.Root, "help", "zeta.md"), Path.Combine(dir.Root, "help"));
        // zeta is explicit and first; the folder expansion must not add it again.
        Assert.Equal(new[] { "zeta.md", "alpha.md" }, names);
    }

    [Fact]
    public void Files_and_directories_follow_the_command_line_order()
    {
        using var dir = new TempTree(("x.md", "#"), ("sub/m.md", "#"), ("y.md", "#"));
        var names = ParseItemNames(
            Path.Combine(dir.Root, "x.md"),
            Path.Combine(dir.Root, "sub"),
            Path.Combine(dir.Root, "y.md"));
        Assert.Equal(new[] { "x.md", "m.md", "y.md" }, names);
    }

    [Fact]
    public void Template_defaults_to_the_MDBOOK_TEMPLATE_environment_variable()
    {
        const string name = "MDBOOK_TEMPLATE";
        var previous = Environment.GetEnvironmentVariable(name);
        Environment.SetEnvironmentVariable(name, "builtin:default.dark.html");
        try
        {
            using var dir = new TempTree(("a.md", "# a"));
            var layer = ParseArgs(Path.Combine(dir.Root, "a.md"));
            Assert.Equal("builtin:default.dark.html", layer.TemplateFilePath);
        }
        finally
        {
            Environment.SetEnvironmentVariable(name, previous);
        }
    }

    [Fact]
    public void Template_argument_overrides_the_MDBOOK_TEMPLATE_environment_variable()
    {
        const string name = "MDBOOK_TEMPLATE";
        var previous = Environment.GetEnvironmentVariable(name);
        Environment.SetEnvironmentVariable(name, "builtin:default.dark.html");
        try
        {
            using var dir = new TempTree(("a.md", "# a"));
            var layer = ParseArgs(Path.Combine(dir.Root, "a.md"), "--template", "builtin:default.light.html");
            Assert.Equal("builtin:default.light.html", layer.TemplateFilePath);
        }
        finally
        {
            Environment.SetEnvironmentVariable(name, previous);
        }
    }

    [Fact]
    public void An_empty_MDBOOK_TEMPLATE_environment_variable_is_ignored()
    {
        const string name = "MDBOOK_TEMPLATE";
        var previous = Environment.GetEnvironmentVariable(name);
        Environment.SetEnvironmentVariable(name, "   ");
        try
        {
            using var dir = new TempTree(("a.md", "# a"));
            var layer = ParseArgs(Path.Combine(dir.Root, "a.md"));
            Assert.Null(layer.TemplateFilePath);
        }
        finally
        {
            Environment.SetEnvironmentVariable(name, previous);
        }
    }

    // --- issue #17: cross-page links resolve to in-file anchors, anchors are path slugs ---

    [Fact]
    public void Single_file_cross_page_link_resolves_to_the_target_page_anchor()
    {
        using var dir = new TempTree(
            ("README.md", "# Home\n\n[appendix](appendix.md)"),
            ("appendix.md", "# Appendix"));
        var html = RenderSingleFile(dir, "all.html",
            Path.Combine(dir.Root, "README.md"), Path.Combine(dir.Root, "appendix.md"));

        Assert.Contains("<article id=\"appendix\">", html);
        Assert.Contains("<a href=\"#appendix\">", html);
        // the broken side-by-side file target must be gone
        Assert.DoesNotContain("appendix.md.html", html);
    }

    [Fact]
    public void Single_file_links_across_subfolders_resolve_both_ways()
    {
        using var dir = new TempTree(
            ("doc/README.md", "# Home\n\n[intro](guide/intro.md)"),
            ("doc/guide/intro.md", "# Intro\n\n[home](../README.md)"));
        var html = RenderSingleFile(dir, "all.html", Path.Combine(dir.Root, "doc"));

        // README -> guide/intro.md , and intro -> ../README.md , both to their slugs
        Assert.Contains("<article id=\"doc-readme\">", html);
        Assert.Contains("<article id=\"doc-guide-intro\">", html);
        Assert.Contains("<a href=\"#doc-guide-intro\">", html);
        Assert.Contains("<a href=\"#doc-readme\">", html);
        Assert.DoesNotContain(".md.html", html);
    }

    [Fact]
    public void Single_file_anchors_are_path_slugs_not_positional()
    {
        using var dir = new TempTree(("doc/README.md", "# Home"), ("doc/appendix.md", "# Appendix"));
        var html = RenderSingleFile(dir, "all.html", Path.Combine(dir.Root, "doc"));

        Assert.DoesNotContain("id=\"page-", html);
        Assert.Contains("<article id=\"doc-readme\">", html);
    }

    [Fact]
    public void Single_file_leaves_links_to_pages_outside_the_bundle_untouched()
    {
        using var dir = new TempTree(("README.md", "# Home\n\n[gone](missing.md) and [ext](https://example.com/)"));
        var html = RenderSingleFile(dir, "all.html", Path.Combine(dir.Root, "README.md"));

        // a .md not in the bundle keeps its file link; an absolute URL stays external
        Assert.Contains("missing.md.html", html);
        Assert.Contains("https://example.com/", html);
    }

    [Fact]
    public void Single_file_deduplicates_colliding_page_slugs()
    {
        // "a-b.md" and "a/b.md" both slug to "<root>-a-b"; the second must be suffixed.
        using var dir = new TempTree(("doc/a-b.md", "# One"), ("doc/a/b.md", "# Two"));
        var html = RenderSingleFile(dir, "all.html", Path.Combine(dir.Root, "doc"));

        Assert.Contains("<article id=\"doc-a-b\">", html);
        Assert.Contains("<article id=\"doc-a-b-2\">", html);
    }

    [Fact]
    public void Single_file_tags_each_article_with_its_language()
    {
        using var dir = new TempTree(("README.en.md", "# Home"), ("guide.fr.md", "# Guide"));
        var html = RenderSingleFile(dir, "all.html",
            Path.Combine(dir.Root, "README.en.md"), Path.Combine(dir.Root, "guide.fr.md"));

        Assert.Contains("<article id=\"readme-en\" lang=\"en\">", html);
        Assert.Contains("<article id=\"guide-fr\" lang=\"fr\">", html);
    }

    [Fact]
    public void Single_file_article_without_a_language_has_no_lang_attribute()
    {
        using var dir = new TempTree(("README.md", "# Home"));
        var html = RenderSingleFile(dir, "all.html", Path.Combine(dir.Root, "README.md"));

        Assert.Contains("<article id=\"readme\">", html);
    }

    // --- issue #18: the table of contents mirrors the source directory tree ---

    [Fact]
    public void Single_file_toc_nests_pages_under_their_folders()
    {
        using var dir = new TempTree(
            ("doc/README.md", "# Home"),
            ("doc/appendix.md", "# Appendix"),
            ("doc/guide/intro.md", "# Intro"));
        var toc = TableOfContents(RenderSingleFile(dir, "all.html", Path.Combine(dir.Root, "doc")));

        // top-level pages (labelled by their H1), then a plain-text "guide" folder with the
        // page nested under it
        Assert.Contains("<li><a href=\"#doc-readme\">Home</a></li>", toc);
        Assert.Contains("<li>guide<ul>", toc);
        Assert.Contains("<li><a href=\"#doc-guide-intro\">Intro</a></li>", toc);
        // the shared root folder is stripped, not shown as a wrapper node
        Assert.DoesNotContain("<li>doc<ul>", toc);
    }

    [Fact]
    public void Single_file_toc_is_flat_when_there_are_no_subfolders()
    {
        using var dir = new TempTree(("a.md", "# A"), ("b.md", "# B"));
        var toc = TableOfContents(RenderSingleFile(dir, "all.html",
            Path.Combine(dir.Root, "a.md"), Path.Combine(dir.Root, "b.md")));

        Assert.Contains("<li><a href=\"#a\">A</a></li>", toc);
        Assert.DoesNotContain("<ul>\n<ul>", toc); // no nested list
    }

    [Fact]
    public void Single_file_toc_labels_use_the_article_h1_title()
    {
        using var dir = new TempTree(("readme.md", "# Welcome Aboard\n\nhi"));
        var toc = TableOfContents(RenderSingleFile(dir, "all.html", Path.Combine(dir.Root, "readme.md")));

        Assert.Contains("<li><a href=\"#readme\">Welcome Aboard</a></li>", toc);
    }

    [Fact]
    public void Single_file_toc_label_falls_back_to_the_filename_without_md_when_no_heading()
    {
        using var dir = new TempTree(("notes.md", "Just a paragraph, no heading."));
        var toc = TableOfContents(RenderSingleFile(dir, "all.html", Path.Combine(dir.Root, "notes.md")));

        Assert.Contains("<li><a href=\"#notes\">notes</a></li>", toc);
        Assert.DoesNotContain("notes.md</a>", toc);
    }

    // Extracts the "<article id=list>...</article>" table-of-contents block.
    private static string TableOfContents(string html)
    {
        var start = html.IndexOf("<article id=list>", StringComparison.Ordinal);
        var end = html.IndexOf("</article>", start, StringComparison.Ordinal);
        return html.Substring(start, end - start);
    }

    // Runs the whole pipeline into a single file and returns its HTML.
    private static string RenderSingleFile(TempTree dir, string singleFileName, params string[] inputs)
    {
        var single = Path.Combine(dir.Root, singleFileName);
        RunCli(inputs.Concat(new[] { "--single-file", single }).ToArray());
        return File.ReadAllText(single);
    }

    // Runs the CLI parse task and returns the source file names in layer order.
    private static string[] ParseItemNames(params string[] args)
    {
        return ParseArgs(args).Items.Select(item => item.SourceFile.Name).ToArray();
    }

    // Runs only the CLI parse task and returns the populated markdown layer.
    private static SimpleMarkdownToHtmlLayer ParseArgs(params string[] args)
    {
        var context = new PackageContext();
        context.AddLayer(new CommandLineLayer(new StringWriter(), new StringWriter(), new StringReader(string.Empty), args));
        var task = new CommandLineMarkdownToHtmlPrepareTask();
        task.Visit(context);
        return context.RequireSingleLayer<SimpleMarkdownToHtmlLayer>();
    }

    // Renders one source file through the real render task with a chosen SideBySide setting.
    private static SimpleMarkdownToHtmlLayerItem RenderSingleFile(TempTree dir, string relativePath, bool sideBySide)
    {
        var layer = new SimpleMarkdownToHtmlLayer();
        layer.SideBySide = sideBySide;
        var item = layer.AddFile(new FileInfo(Path.Combine(dir.Root, relativePath)), true);
        item.RelativePath = new[] { Path.GetFileName(relativePath) };

        var context = new PackageContext();
        context.AddLayer(layer);
        var task = new SimpleMarkdownToHtmlTask();
        task.Visit(context);
        task.Run(context);
        return item;
    }

    // Runs the whole task pipeline exactly as Program.cs does, with the built-in template.
    private static void RunCli(params string[] args)
    {
        var context = new PackageContext();
        context.AddLayer(new CommandLineLayer(new StringWriter(), new StringWriter(), new StringReader(string.Empty),
            args.Concat(new[] { "--template", "builtin:default.light.html" }).ToArray()));
        var tasks = new ITask[]
        {
            new CommandLineMarkdownToHtmlPrepareTask(),
            new SimpleMarkdownToHtmlTask(),
            new ExportMarkdownToHtmlTask(),
            new CombineMarkdownToHtmlTask(),
        };
        foreach (var task in tasks)
        {
            task.Visit(context);
        }

        foreach (var task in tasks)
        {
            task.Verify(context);
        }

        foreach (var task in tasks)
        {
            task.Run(context);
        }
    }

    // A throwaway directory tree of source files, removed on dispose.
    private sealed class TempTree : IDisposable
    {
        public TempTree(params (string Path, string Body)[] files)
        {
            this.Root = Path.Combine(Path.GetTempPath(), "mdbook-tests-" + Guid.NewGuid().ToString("N"));
            Directory.CreateDirectory(this.Root);
            foreach (var (relativePath, body) in files)
            {
                var full = Path.Combine(this.Root, relativePath);
                Directory.CreateDirectory(Path.GetDirectoryName(full)!);
                File.WriteAllText(full, body, Encoding.UTF8);
            }
        }

        public string Root { get; }

        public void Dispose()
        {
            try
            {
                Directory.Delete(this.Root, true);
            }
            catch (DirectoryNotFoundException)
            {
            }
        }
    }
}
