// Generated by Claude Opus 4.8 (claude.ai/code) · 2026-09-07
namespace Airudit.MdBook.UnitTests;

using Airudit.MdBook.Core;
using System.Text;

/// <summary>
/// Rendering behaviour of <see cref="SimpleMarkdownToHtmlTask"/>: template
/// placeholders, language detection and link rewriting.
/// </summary>
public class SimpleMarkdownToHtmlTaskTests
{
    // A minimal template exercising every substituted placeholder, so assertions
    // do not depend on the built-in template markup.
    private const string Template =
        "<!doctype html>\n" +
        "<html lang=\"{{{Lang}}}\">\n" +
        "<head><title>{{{PageTitle}}}</title></head>\n" +
        "<body>{{{Contents}}}<footer>{{{Copyright}}}</footer></body>\n" +
        "</html>\n";

    [Fact]
    public void Copyright_is_substituted_in_per_file_output()
    {
        var html = RenderToHtml("doc.md", "# Hello", copyright: "Copyright 2026 Airudit");
        Assert.Contains("Copyright 2026 Airudit", html);
    }

    [Fact]
    public void PageTitle_comes_from_the_file_name()
    {
        var html = RenderToHtml("guide.md", "# Hello");
        Assert.Contains("<title>guide</title>", html);
    }

    [Fact]
    public void Language_suffix_sets_lang_and_is_stripped_from_the_title()
    {
        var html = RenderToHtml("guide.en.md", "# Hello");
        Assert.Contains("lang=\"en\"", html);
        Assert.Contains("<title>guide</title>", html);
    }

    [Fact]
    public void Language_defaults_to_en_without_a_suffix()
    {
        var html = RenderToHtml("guide.md", "# Hello");
        Assert.Contains("lang=\"en\"", html);
    }

    [Fact]
    public void Local_markdown_links_are_rewritten_to_html()
    {
        var html = RenderToHtml("doc.md", "[other](other.md)");
        Assert.Contains("href=\"other.md.html\"", html);
    }

    [Fact]
    public void External_links_get_the_external_class()
    {
        var html = RenderToHtml("doc.md", "[site](https://example.com)");
        Assert.Contains("class=\"external\"", html);
    }

    // --- {{include: ...}} directive — behaviour that must be preserved ---

    [Fact]
    public void Include_splices_the_referenced_file_content()
    {
        var html = RenderTreeToHtml("main.md", new[]
        {
            ("main.md", "{{include: part.md}}"),
            ("part.md", "spliced-marker"),
        });
        Assert.Contains("spliced-marker", html);
    }

    [Fact]
    public void Include_of_a_missing_file_emits_a_comment()
    {
        var html = RenderTreeToHtml("main.md", new[]
        {
            ("main.md", "{{include: nope.md}}"),
        });
        Assert.Contains("NO SUCH FILE", html);
    }

    [Fact]
    public void Include_of_a_non_markdown_file_is_rejected()
    {
        var html = RenderTreeToHtml("main.md", new[]
        {
            ("main.md", "{{include: data.txt}}"),
            ("data.txt", "raw"),
        });
        Assert.Contains("INVALID FILE EXTENSION", html);
    }

    [Fact]
    public void Include_with_a_leading_slash_resolves_from_the_source_directory()
    {
        var html = RenderTreeToHtml("main.md", new[]
        {
            ("main.md", "{{include: /part.md}}"),
            ("part.md", "slash-marker"),
        });
        Assert.Contains("slash-marker", html);
    }

    [Fact]
    public void Link_in_a_same_folder_include_is_rewritten_to_html()
    {
        var html = RenderTreeToHtml("main.md", new[]
        {
            ("main.md", "{{include: part.md}}"),
            ("part.md", "[o](other.md)"),
        });
        Assert.Contains("href=\"other.md.html\"", html);
    }

    // --- issue #7: relative links inside an included file must be rebased ---

    [Fact]
    public void Link_in_an_included_file_is_rebased_to_its_folder()
    {
        var html = RenderTreeToHtml("main.md", new[]
        {
            ("main.md", "{{include: help/readme.md}}"),
            ("help/readme.md", "[p1](page1.md)"),
        });
        Assert.Contains("href=\"help/page1.md.html\"", html);
    }

    [Fact]
    public void Subfolder_link_in_an_included_file_is_rebased()
    {
        var html = RenderTreeToHtml("main.md", new[]
        {
            ("main.md", "{{include: help/readme.md}}"),
            ("help/readme.md", "[p2](pages/page2.md)"),
        });
        Assert.Contains("href=\"help/pages/page2.md.html\"", html);
    }

    [Fact]
    public void Parent_relative_link_in_an_included_file_collapses()
    {
        var html = RenderTreeToHtml("main.md", new[]
        {
            ("main.md", "{{include: a/b/part.md}}"),
            ("a/b/part.md", "[x](../x.md)"),
        });
        Assert.Contains("href=\"a/x.md.html\"", html);
    }

    [Fact]
    public void Nested_includes_are_expanded()
    {
        var html = RenderTreeToHtml("main.md", new[]
        {
            ("main.md", "{{include: a.md}}"),
            ("a.md", "# A\n\n{{include: b.md}}"),
            ("b.md", "bee-marker"),
        });
        Assert.Contains("bee-marker", html);
    }

    [Fact]
    public void A_file_that_includes_itself_does_not_loop()
    {
        var html = RenderTreeToHtml("main.md", new[]
        {
            ("main.md", "top-marker\n\n{{include: main.md}}"),
        });
        Assert.Contains("top-marker", html);
        Assert.Contains("cycle", html);
    }

    [Fact]
    public void An_indirect_include_cycle_does_not_loop()
    {
        var html = RenderTreeToHtml("main.md", new[]
        {
            ("main.md", "{{include: a.md}}"),
            ("a.md", "aaa-marker\n\n{{include: b.md}}"),
            ("b.md", "bbb-marker\n\n{{include: a.md}}"),
        });
        Assert.Contains("aaa-marker", html);
        Assert.Contains("bbb-marker", html);
        Assert.Contains("cycle", html);
    }

    // --- links outside paragraphs (headings, lists) must be rewritten too ---

    [Fact]
    public void Markdown_link_inside_a_heading_is_rewritten()
    {
        var html = RenderTreeToHtml("main.md", new[]
        {
            ("main.md", "# See [x](other.md)"),
        });
        Assert.Contains("href=\"other.md.html\"", html);
    }

    // --- issue #15: numbered setext headings (1. Title + ----) must render as a
    // heading, not an ordered-list item followed by a stray thematic break ---

    [Fact]
    public void Numbered_setext_heading_renders_as_h2_not_list_and_hr()
    {
        var html = RenderToHtml("doc.md", "1. Contexte et origine\n----------------------");
        Assert.Contains("<h2", html);
        Assert.DoesNotContain("<hr", html);
        Assert.DoesNotContain("<ol", html);
    }

    [Fact]
    public void Numbered_setext_heading_keeps_the_number_in_its_text()
    {
        var html = RenderToHtml("doc.md", "1. Contexte et origine\n----------------------");
        Assert.Contains("1. Contexte et origine", html);
        Assert.DoesNotContain("1\\.", html);
    }

    [Fact]
    public void Consecutive_numbered_setext_headings_do_not_continue_list_numbering()
    {
        var html = RenderToHtml("doc.md",
            "1. First\n--------\n\nBody.\n\n2. Second\n---------");
        Assert.DoesNotContain("start=\"2\"", html);
        Assert.DoesNotContain("<ol", html);
        Assert.DoesNotContain("<hr", html);
    }

    [Fact]
    public void Numbered_setext_heading_with_a_paren_marker_is_fixed()
    {
        var html = RenderToHtml("doc.md", "1) Contexte\n----------");
        Assert.Contains("<h2", html);
        Assert.Contains("1) Contexte", html);
        Assert.DoesNotContain("<hr", html);
    }

    [Fact]
    public void Numbered_setext_heading_with_equals_underline_renders_as_h1()
    {
        var html = RenderToHtml("doc.md", "1. Title\n========");
        Assert.Contains("<h1", html);
        Assert.Contains("1. Title", html);
        Assert.DoesNotContain("<ol", html);
    }

    [Fact]
    public void Numbered_list_with_a_blank_line_before_the_underline_stays_a_list()
    {
        // Blank line between the item and the dashes: not an underline candidate,
        // so this is a genuine list + page break — the fix must not trigger.
        var html = RenderToHtml("doc.md", "1. An item\n\n----------");
        Assert.Contains("<li>", html);
    }

    [Fact]
    public void Numbered_setext_inside_a_fenced_code_block_is_left_untouched()
    {
        var html = RenderToHtml("doc.md", "```\n1. Sample\n--------\n```");
        // Code content is preserved literally, with no injected backslash escape.
        Assert.Contains("1. Sample", html);
        Assert.DoesNotContain("1\\.", html);
    }

    [Fact]
    public void Numbered_setext_fix_can_be_disabled_with_the_environment_variable()
    {
        const string name = "MDBOOK_NUMBERED_SETEXT_FIX";
        var previous = Environment.GetEnvironmentVariable(name);
        Environment.SetEnvironmentVariable(name, "0");
        try
        {
            var html = RenderToHtml("doc.md", "1. Title\n--------");
            // Fix off: original CommonMark behaviour (ordered list + stray hr) returns.
            Assert.Contains("<ol", html);
            Assert.Contains("<hr", html);
        }
        finally
        {
            Environment.SetEnvironmentVariable(name, previous);
        }
    }

    // Renders one Markdown file through the real task and returns the output HTML.
    private static string RenderToHtml(string fileName, string markdown, string? copyright = null)
    {
        var tempDir = Path.Combine(Path.GetTempPath(), "mdbook-tests-" + Guid.NewGuid().ToString("N"));
        Directory.CreateDirectory(tempDir);
        try
        {
            var templatePath = Path.Combine(tempDir, "template.html");
            File.WriteAllText(templatePath, Template, Encoding.UTF8);

            var sourcePath = Path.Combine(tempDir, fileName);
            File.WriteAllText(sourcePath, markdown, Encoding.UTF8);

            var layer = new SimpleMarkdownToHtmlLayer();
            layer.AddFile(new FileInfo(sourcePath), true);
            layer.TemplateFilePath = templatePath;
            layer.Copyright = copyright;

            var context = new PackageContext();
            context.AddLayer(layer);
            var task = new SimpleMarkdownToHtmlTask();
            task.Visit(context);
            task.Run(context);

            return File.ReadAllText(sourcePath + ".html", Encoding.UTF8);
        }
        finally
        {
            Directory.Delete(tempDir, true);
        }
    }

    // Writes a small tree of Markdown files to a temp directory, renders the host
    // file through the real task, and returns its output HTML. Used for {{include}}
    // scenarios where the layout of neighbouring files matters.
    private static string RenderTreeToHtml(string hostRelativePath, (string Path, string Body)[] files, string? copyright = null)
    {
        var tempDir = System.IO.Path.Combine(System.IO.Path.GetTempPath(), "mdbook-tests-" + Guid.NewGuid().ToString("N"));
        Directory.CreateDirectory(tempDir);
        try
        {
            var templatePath = System.IO.Path.Combine(tempDir, "template.html");
            File.WriteAllText(templatePath, Template, Encoding.UTF8);

            foreach (var (relativePath, body) in files)
            {
                var fullPath = System.IO.Path.Combine(tempDir, relativePath);
                Directory.CreateDirectory(System.IO.Path.GetDirectoryName(fullPath)!);
                File.WriteAllText(fullPath, body, Encoding.UTF8);
            }

            var hostPath = System.IO.Path.Combine(tempDir, hostRelativePath);
            var layer = new SimpleMarkdownToHtmlLayer();
            layer.AddFile(new FileInfo(hostPath), true);
            layer.TemplateFilePath = templatePath;
            layer.Copyright = copyright;

            var context = new PackageContext();
            context.AddLayer(layer);
            var task = new SimpleMarkdownToHtmlTask();
            task.Visit(context);
            task.Run(context);

            return File.ReadAllText(hostPath + ".html", Encoding.UTF8);
        }
        finally
        {
            Directory.Delete(tempDir, true);
        }
    }
}
