// Generated by Claude Opus 4.8 (claude.ai/code) · 2026-09-07
namespace Airudit.MdBook.UnitTests;

using Airudit.MdBook.Core;
using System.Text;

/// <summary>
/// Rendering behaviour of <see cref="SimpleMarkdownToHtmlTask"/>: template
/// placeholders, language detection and link rewriting.
/// </summary>
public class SimpleMarkdownToHtmlTaskTests
{
    // A minimal template exercising every substituted placeholder, so assertions
    // do not depend on the built-in template markup.
    private const string Template =
        "<!doctype html>\n" +
        "<html lang=\"{{{Lang}}}\">\n" +
        "<head><title>{{{PageTitle}}}</title></head>\n" +
        "<body>{{{Contents}}}<footer>{{{Copyright}}}</footer></body>\n" +
        "</html>\n";

    [Fact]
    public void Copyright_is_substituted_in_per_file_output()
    {
        var html = RenderToHtml("doc.md", "# Hello", copyright: "Copyright 2026 Airudit");
        Assert.Contains("Copyright 2026 Airudit", html);
    }

    [Fact]
    public void PageTitle_comes_from_the_file_name()
    {
        var html = RenderToHtml("guide.md", "# Hello");
        Assert.Contains("<title>guide</title>", html);
    }

    [Fact]
    public void Language_suffix_sets_lang_and_is_stripped_from_the_title()
    {
        var html = RenderToHtml("guide.en.md", "# Hello");
        Assert.Contains("lang=\"en\"", html);
        Assert.Contains("<title>guide</title>", html);
    }

    [Fact]
    public void Language_defaults_to_en_without_a_suffix()
    {
        var html = RenderToHtml("guide.md", "# Hello");
        Assert.Contains("lang=\"en\"", html);
    }

    [Fact]
    public void Local_markdown_links_are_rewritten_to_html()
    {
        var html = RenderToHtml("doc.md", "[other](other.md)");
        Assert.Contains("href=\"other.md.html\"", html);
    }

    [Fact]
    public void External_links_get_the_external_class()
    {
        var html = RenderToHtml("doc.md", "[site](https://example.com)");
        Assert.Contains("class=\"external\"", html);
    }

    // Renders one Markdown file through the real task and returns the output HTML.
    private static string RenderToHtml(string fileName, string markdown, string? copyright = null)
    {
        var tempDir = Path.Combine(Path.GetTempPath(), "mdbook-tests-" + Guid.NewGuid().ToString("N"));
        Directory.CreateDirectory(tempDir);
        try
        {
            var templatePath = Path.Combine(tempDir, "template.html");
            File.WriteAllText(templatePath, Template, Encoding.UTF8);

            var sourcePath = Path.Combine(tempDir, fileName);
            File.WriteAllText(sourcePath, markdown, Encoding.UTF8);

            var layer = new SimpleMarkdownToHtmlLayer();
            layer.AddFile(new FileInfo(sourcePath), true);
            layer.TemplateFilePath = templatePath;
            layer.Copyright = copyright;

            var context = new PackageContext();
            context.AddLayer(layer);
            var task = new SimpleMarkdownToHtmlTask();
            task.Visit(context);
            task.Run(context);

            return File.ReadAllText(sourcePath + ".html", Encoding.UTF8);
        }
        finally
        {
            Directory.Delete(tempDir, true);
        }
    }
}
