// Generated by Claude Opus 4.8 (claude.ai/code) · 2026-09-15
namespace Airudit.MdBook.UnitTests;

using Airudit.MdBook.Core;

/// <summary>
/// The <c>{{{HighlightStyles}}}</c> placeholder generator (issue #25): theme CSS is produced from
/// ColorCode at render time rather than hard-coded into the templates.
/// </summary>
public class SyntaxHighlightingTests
{
    [Fact]
    public void Recognises_the_light_and_dark_placeholder_keys()
    {
        Assert.True(HighlightStylesheet.IsPlaceholder("HighlightStyles"));
        Assert.True(HighlightStylesheet.IsPlaceholder("HighlightStyles.dark"));
        Assert.False(HighlightStylesheet.IsPlaceholder("Contents"));
        Assert.False(HighlightStylesheet.IsPlaceholder("HighlightStyles.pink"));
    }

    [Fact]
    public void Light_placeholder_emits_scoped_token_rules()
    {
        var css = HighlightStylesheet.Render("HighlightStyles", highlightingEnabled: true);
        Assert.Contains("pre code .keyword", css);
        Assert.Contains("pre code { color:", css); // base text colour
        Assert.DoesNotContain("plainText", css);   // wrapper class dropped
    }

    [Fact]
    public void Dark_placeholder_uses_the_dark_theme_colours()
    {
        var css = HighlightStylesheet.Render("HighlightStyles.dark", highlightingEnabled: true);
        // VS-dark keyword blue; absent from the light theme.
        Assert.Contains("#569cd6", css);
    }

    [Fact]
    public void Disabled_highlighting_emits_no_css()
    {
        Assert.Equal(string.Empty, HighlightStylesheet.Render("HighlightStyles", highlightingEnabled: false));
        Assert.Equal(string.Empty, HighlightStylesheet.Render("HighlightStyles.dark", highlightingEnabled: false));
    }

    [Fact]
    public void Colours_are_sanitised_to_six_digit_hex()
    {
        var css = HighlightStylesheet.Render("HighlightStyles", highlightingEnabled: true);
        // No leftover ARGB alpha or malformed values (e.g. "#ff0000ff" or "#ff#e6e6e6").
        Assert.DoesNotContain("color: #ff0000ff", css);
        Assert.DoesNotContain("##", css);
    }

    // --- issue #25: a malformed block must not hang the highlighter (ColorCode backtracking) ---

    [Fact]
    public void Match_timeout_defaults_to_one_second()
    {
        var previous = Environment.GetEnvironmentVariable("MDBOOK_HIGHLIGHT_TIMEOUT_MS");
        Environment.SetEnvironmentVariable("MDBOOK_HIGHLIGHT_TIMEOUT_MS", null);
        try
        {
            Assert.Equal(1000, SyntaxHighlightingExtension.ResolveMatchTimeout().TotalMilliseconds);
        }
        finally
        {
            Environment.SetEnvironmentVariable("MDBOOK_HIGHLIGHT_TIMEOUT_MS", previous);
        }
    }

    [Fact]
    public void Match_timeout_honours_the_environment_variable()
    {
        var previous = Environment.GetEnvironmentVariable("MDBOOK_HIGHLIGHT_TIMEOUT_MS");
        Environment.SetEnvironmentVariable("MDBOOK_HIGHLIGHT_TIMEOUT_MS", "250");
        try
        {
            Assert.Equal(250, SyntaxHighlightingExtension.ResolveMatchTimeout().TotalMilliseconds);
        }
        finally
        {
            Environment.SetEnvironmentVariable("MDBOOK_HIGHLIGHT_TIMEOUT_MS", previous);
        }
    }
}
