// Generated by Claude Opus 4.8 (claude.ai/code) · 2026-09-15
namespace Airudit.MdBook.Core
{
    using System;
    using System.Collections.Generic;
    using System.Diagnostics;
    using System.IO;
    using System.Linq;
    using System.Net.Http;
    using System.Runtime.InteropServices;
    using System.Text;

    /// <summary>
    /// Renders one diagram's source to an SVG string. Implementations are best-effort: any failure
    /// (tool absent, non-zero exit, timeout, HTTP error) returns <c>false</c> so the caller falls
    /// back to a plain code block. A render must never throw or stall (issue #5).
    /// </summary>
    public interface IDiagramProvider
    {
        /// <summary>True when this provider can render the given fence tag (e.g. "mermaid").</summary>
        bool CanRender(string diagramTag);

        /// <summary>
        /// Renders <paramref name="source"/> for <paramref name="diagramTag"/> to SVG. Returns false
        /// (with <paramref name="svg"/> empty) on any failure.
        /// </summary>
        bool TryRenderSvg(string diagramTag, string source, DiagramColorScheme scheme, out string svg);
    }

    /// <summary>The provider used when diagram rendering is off: renders nothing.</summary>
    internal sealed class NoneDiagramProvider : IDiagramProvider
    {
        public bool CanRender(string diagramTag)
        {
            return false;
        }

        public bool TryRenderSvg(string diagramTag, string source, DiagramColorScheme scheme, out string svg)
        {
            svg = string.Empty;
            return false;
        }
    }

    /// <summary>How a one-shot docker renderer receives its source and yields its SVG.</summary>
    internal enum DockerIo
    {
        /// <summary>Source is written to a mounted input file; the SVG is read from a mounted output file.</summary>
        FileToFile,

        /// <summary>Source is piped to the container's stdin; the SVG is read from its stdout.</summary>
        PipeToStdout,
    }

    /// <summary>
    /// One entry in the docker renderer registry: pure data describing which fence tags it handles,
    /// the pinned image, its I/O mode, and how to build the per-run arguments (theme-aware). Adding a
    /// renderer is adding one of these records — no new control flow.
    /// </summary>
    internal sealed record DockerRenderer(
        string[] Tags,
        string Image,
        DockerIo Io,
        string InputExtension,
        Func<DiagramColorScheme, string, string, string[]> BuildArgs);

    /// <summary>
    /// Runs diagrams through one-shot <c>docker run</c> invocations from a hard-coded registry. Fully
    /// local: the source never leaves the machine. Ships mermaid and plantuml; more renderers are new
    /// registry records (issue #5). Image versions are pinned so a render is reproducible.
    /// </summary>
    public sealed class DockerDiagramProvider : IDiagramProvider
    {
        // Pinned image versions — never ":latest", so renders can't silently change under the docs.
        private const string MermaidImage = "minlag/mermaid-cli:11.4.2";
        private const string PlantumlImage = "plantuml/plantuml:1.2025.2";

        private static readonly DockerRenderer[] Registry =
        {
            // mermaid: file in, file out. -e/-t/-s are the maintainer's known-good args; -b transparent
            // keeps the diagram theme-neutral so it sits on the page background (light or dark template).
            new DockerRenderer(
                new[] { "mermaid" },
                MermaidImage,
                DockerIo.FileToFile,
                "mmd",
                (scheme, input, output) => new[]
                {
                    "-e", "svg",
                    "-t", MermaidTheme(scheme),
                    "-s", "3",
                    "-b", "transparent",
                    "-i", input,
                    "-o", output,
                }),

            // plantuml: source piped to stdin, SVG read from stdout (-pipe -tsvg). PlantUML has no
            // simple dark switch, so the colour scheme is not applied here (light rendering) for v1.
            new DockerRenderer(
                new[] { "plantuml", "puml" },
                PlantumlImage,
                DockerIo.PipeToStdout,
                "puml",
                (scheme, input, output) => new[] { "-pipe", "-tsvg" }),
        };

        /// <summary>Every fence tag any docker renderer handles.</summary>
        public static IReadOnlyCollection<string> Tags { get; } =
            new HashSet<string>(Registry.SelectMany(r => r.Tags), StringComparer.OrdinalIgnoreCase);

        private readonly Action<string>? log;

        public DockerDiagramProvider(Action<string>? log = null)
        {
            this.log = log;
        }

        public bool CanRender(string diagramTag)
        {
            return Find(diagramTag) != null;
        }

        public bool TryRenderSvg(string diagramTag, string source, DiagramColorScheme scheme, out string svg)
        {
            svg = string.Empty;
            var renderer = Find(diagramTag);
            if (renderer == null)
            {
                return false;
            }

            try
            {
                return renderer.Io == DockerIo.FileToFile
                    ? this.RunFileToFile(renderer, source, scheme, out svg)
                    : this.RunPipeToStdout(renderer, source, scheme, out svg);
            }
            catch (Exception ex)
            {
                // Docker missing (Win32Exception), I/O error, etc. — best-effort, fall back to plain.
                this.log?.Invoke("Diagram \"" + diagramTag + "\" via Docker (" + renderer.Image + "): " + ex.GetType().Name + ": " + ex.Message);
                svg = string.Empty;
                return false;
            }
        }

        private static DockerRenderer? Find(string diagramTag)
        {
            if (string.IsNullOrEmpty(diagramTag))
            {
                return null;
            }

            foreach (var renderer in Registry)
            {
                if (renderer.Tags.Contains(diagramTag, StringComparer.OrdinalIgnoreCase))
                {
                    return renderer;
                }
            }

            return null;
        }

        private bool RunFileToFile(DockerRenderer renderer, string source, DiagramColorScheme scheme, out string svg)
        {
            svg = string.Empty;
            var work = new DirectoryInfo(Path.Combine(Path.GetTempPath(), "mdbook-diagram-" + Guid.NewGuid().ToString("N")));
            work.Create();
            try
            {
                var inputFile = Path.Combine(work.FullName, "input." + renderer.InputExtension);
                var outputFile = Path.Combine(work.FullName, "output.svg");
                File.WriteAllText(inputFile, source, new UTF8Encoding(false));

                var args = new List<string> { "run", "--rm" };
                var user = CurrentUserSpec();
                if (user != null)
                {
                    args.Add("-u");
                    args.Add(user);
                }

                args.Add("-v");
                args.Add(work.FullName + ":/data");
                args.Add(renderer.Image);
                args.AddRange(renderer.BuildArgs(scheme, "/data/input." + renderer.InputExtension, "/data/output.svg"));

                if (!this.RunDocker(args, stdin: null, out _, out var stderr, out var exitCode))
                {
                    return false; // start failure / timeout already logged
                }

                if (exitCode != 0)
                {
                    this.log?.Invoke("Diagram via Docker (" + renderer.Image + ") exited " + exitCode + ". " + FirstLine(stderr));
                    return false;
                }

                if (!File.Exists(outputFile))
                {
                    this.log?.Invoke("Diagram via Docker (" + renderer.Image + "): no output produced. " + FirstLine(stderr));
                    return false;
                }

                svg = File.ReadAllText(outputFile, Encoding.UTF8);
                if (svg.IndexOf("<svg", StringComparison.OrdinalIgnoreCase) < 0)
                {
                    this.log?.Invoke("Diagram via Docker (" + renderer.Image + "): output was not SVG. ");
                    return false;
                }

                return true;
            }
            finally
            {
                try
                {
                    work.Delete(true);
                }
                catch (IOException)
                {
                }
            }
        }

        private bool RunPipeToStdout(DockerRenderer renderer, string source, DiagramColorScheme scheme, out string svg)
        {
            svg = string.Empty;
            var args = new List<string> { "run", "--rm", "-i", renderer.Image };
            args.AddRange(renderer.BuildArgs(scheme, string.Empty, string.Empty));

            if (!this.RunDocker(args, stdin: source, out var stdout, out var stderr, out var exitCode))
            {
                return false; // start failure / timeout already logged
            }

            if (exitCode != 0)
            {
                this.log?.Invoke("Diagram via Docker (" + renderer.Image + ") exited " + exitCode + ". " + FirstLine(stderr));
                return false;
            }

            svg = stdout;
            if (svg.IndexOf("<svg", StringComparison.OrdinalIgnoreCase) < 0)
            {
                this.log?.Invoke("Diagram via Docker (" + renderer.Image + "): output was not SVG. " + FirstLine(stderr));
                return false;
            }

            return true;
        }

        // Runs a docker command, optionally feeding stdin, capturing stdout and stderr, bounded by the
        // diagram timeout. Returns false (logging why) when the process could not be started or timed
        // out; a non-zero exit still returns true, leaving the caller to interpret <paramref name="exitCode"/>.
        private bool RunDocker(IReadOnlyList<string> args, string? stdin, out string stdout, out string stderr, out int exitCode)
        {
            stdout = string.Empty;
            stderr = string.Empty;
            exitCode = -1;

            var info = new ProcessStartInfo("docker")
            {
                RedirectStandardOutput = true,
                RedirectStandardError = true,
                RedirectStandardInput = stdin != null,
                UseShellExecute = false,
                CreateNoWindow = true,
            };
            foreach (var arg in args)
            {
                info.ArgumentList.Add(arg);
            }

            using var process = Process.Start(info);
            if (process == null)
            {
                this.log?.Invoke("Docker could not be started (is Docker installed and on PATH?). ");
                return false;
            }

            if (stdin != null)
            {
                process.StandardInput.Write(stdin);
                process.StandardInput.Close();
            }

            var output = process.StandardOutput.ReadToEnd();
            var errors = process.StandardError.ReadToEnd();
            if (!process.WaitForExit((int)DiagramRuntime.Timeout.TotalMilliseconds))
            {
                try
                {
                    process.Kill(true);
                }
                catch (Exception)
                {
                }

                this.log?.Invoke("Docker render timed out after " + (int)DiagramRuntime.Timeout.TotalSeconds + "s. ");
                return false;
            }

            stdout = output;
            stderr = errors;
            exitCode = process.ExitCode;
            return true;
        }

        // The first non-empty line of a process's stderr, trimmed, for a compact --verbose message.
        private static string FirstLine(string text)
        {
            if (string.IsNullOrWhiteSpace(text))
            {
                return string.Empty;
            }

            foreach (var line in text.Split('\n'))
            {
                var trimmed = line.Trim();
                if (trimmed.Length > 0)
                {
                    return trimmed.Length > 200 ? trimmed.Substring(0, 200) : trimmed;
                }
            }

            return string.Empty;
        }

        private static string MermaidTheme(DiagramColorScheme scheme)
        {
            return scheme == DiagramColorScheme.Dark ? "dark" : "default";
        }

        // "uid:gid" on Linux so container-written files are owned by us (not root); null elsewhere,
        // where -u is unnecessary or unsupported (Docker Desktop). getuid/getgid can't fail, but the
        // p/invoke is guarded so a non-Linux or restricted host just skips -u.
        private static string? CurrentUserSpec()
        {
            if (!RuntimeInformation.IsOSPlatform(OSPlatform.Linux))
            {
                return null;
            }

            try
            {
                return Getuid() + ":" + Getgid();
            }
            catch (Exception)
            {
                return null;
            }
        }

        [DllImport("libc", EntryPoint = "getuid")]
        private static extern uint Getuid();

        [DllImport("libc", EntryPoint = "getgid")]
        private static extern uint Getgid();
    }

    /// <summary>
    /// Renders diagrams through a Kroki server (public or self-hosted): POSTs the raw source to
    /// <c>{url}{tag}/svg</c> and returns the SVG body. One integration covers mermaid and the whole
    /// Kroki diagram set. A public endpoint uploads the source to a third party, so it is only ever
    /// reached when its URL is set explicitly (issue #5).
    /// </summary>
    public sealed class KrokiDiagramProvider : IDiagramProvider
    {
        // Per conventions: one long-lived HttpClient (never per-call) with a bounded timeout.
        private static readonly HttpClient Http = CreateClient();

        // Kroki diagram types this provider will POST. Unknown tags are left to fall back to plain.
        private static readonly HashSet<string> Supported = new(StringComparer.OrdinalIgnoreCase)
        {
            "mermaid", "plantuml", "graphviz", "d2", "ditaa", "erd", "blockdiag", "seqdiag", "actdiag",
            "nwdiag", "packetdiag", "rackdiag", "c4plantuml", "bpmn", "bytefield", "nomnoml", "pikchr",
            "structurizr", "svgbob", "umlet", "vega", "vegalite", "wavedrom", "wireviz", "dbml", "tikz",
            "excalidraw", "symbolator", "diagramsnet",
        };

        private readonly string baseUrl;
        private readonly Action<string>? log;

        public KrokiDiagramProvider(string krokiUrl, Action<string>? log = null)
        {
            if (string.IsNullOrWhiteSpace(krokiUrl))
            {
                throw new ArgumentException("A Kroki base URL is required. ", nameof(krokiUrl));
            }

            // Normalise to a trailing slash so "{url}{tag}/svg" joins correctly even if the user
            // passed "https://kroki.io" without the authority/path separator.
            this.baseUrl = krokiUrl.EndsWith("/", StringComparison.Ordinal) ? krokiUrl : krokiUrl + "/";
            this.log = log;
        }

        /// <summary>Every fence tag this provider will attempt via Kroki.</summary>
        public static IReadOnlyCollection<string> Tags { get; } = Supported;

        public bool CanRender(string diagramTag)
        {
            return diagramTag != null && Supported.Contains(diagramTag);
        }

        public bool TryRenderSvg(string diagramTag, string source, DiagramColorScheme scheme, out string svg)
        {
            svg = string.Empty;
            if (!this.CanRender(diagramTag))
            {
                return false;
            }

            try
            {
                var body = ApplyScheme(diagramTag, source, scheme);
                using var request = new HttpRequestMessage(HttpMethod.Post, this.baseUrl + diagramTag.ToLowerInvariant() + "/svg")
                {
                    Content = new StringContent(body, new UTF8Encoding(false), "text/plain"),
                };

                using var response = Http.Send(request);
                if (!response.IsSuccessStatusCode)
                {
                    this.log?.Invoke("Diagram \"" + diagramTag + "\" via Kroki: HTTP " + (int)response.StatusCode + ". ");
                    return false;
                }

                using var stream = response.Content.ReadAsStream();
                using var reader = new StreamReader(stream, Encoding.UTF8);
                svg = reader.ReadToEnd();
                return svg.IndexOf("<svg", StringComparison.OrdinalIgnoreCase) >= 0;
            }
            catch (Exception ex)
            {
                // Unreachable, timeout, non-2xx already handled — any error means fall back to plain.
                this.log?.Invoke("Diagram \"" + diagramTag + "\" via Kroki: " + ex.GetType().Name + ": " + ex.Message);
                svg = string.Empty;
                return false;
            }
        }

        // Best-effort dark theming: mermaid honours an inline init directive. Other Kroki types have
        // no uniform switch, so they render in their default (light) scheme for v1.
        private static string ApplyScheme(string diagramTag, string source, DiagramColorScheme scheme)
        {
            if (scheme == DiagramColorScheme.Dark
                && "mermaid".Equals(diagramTag, StringComparison.OrdinalIgnoreCase)
                && source.IndexOf("%%{", StringComparison.Ordinal) < 0)
            {
                return "%%{init: {\"theme\":\"dark\"}}%%\n" + source;
            }

            return source;
        }

        private static HttpClient CreateClient()
        {
            var client = new HttpClient();
            client.Timeout = DiagramRuntime.Timeout;
            return client;
        }
    }

    /// <summary>Run-wide diagram settings resolved once from the environment.</summary>
    internal static class DiagramRuntime
    {
        // Per-diagram render budget (docker run / Kroki POST). Generous by default because a first
        // docker run may pull the image; override with MDBOOK_DIAGRAM_TIMEOUT_MS.
        public static TimeSpan Timeout { get; } = ResolveTimeout();

        private static TimeSpan ResolveTimeout()
        {
            const int defaultMs = 120000;
            var raw = Environment.GetEnvironmentVariable("MDBOOK_DIAGRAM_TIMEOUT_MS");
            if (int.TryParse(raw, out var ms) && ms > 0)
            {
                return TimeSpan.FromMilliseconds(ms);
            }

            return TimeSpan.FromMilliseconds(defaultMs);
        }
    }
}
