// Generated by Claude Opus 4.8 (claude.ai/code) · 2026-09-15
namespace Airudit.MdBook.Core
{
    using Markdig;
    using Markdig.Renderers;
    using Markdig.Renderers.Html;
    using Markdig.Syntax;
    using System;
    using System.Collections.Generic;
    using System.Linq;
    using System.Text;
    using System.Text.RegularExpressions;

    /// <summary>Which diagram-rendering provider a run uses (issue #5).</summary>
    public enum DiagramProviderKind
    {
        /// <summary>Do not render; diagram fences fall back to plain blocks (and trigger a warning).</summary>
        None = 0,

        /// <summary>Render locally via one-shot <c>docker run</c> images (mermaid, plantuml, …).</summary>
        Docker,

        /// <summary>Render via a Kroki server (public or self-hosted).</summary>
        Kroki,
    }

    /// <summary>
    /// The colour scheme a template declares, used to pick a matching diagram theme. A rendered SVG
    /// bakes in its colours, so this must match the template or a diagram is unreadable (issue #5).
    /// </summary>
    public enum DiagramColorScheme
    {
        Light = 0,
        Dark,
    }

    /// <summary>
    /// Collects the fence tags of diagrams that were present but not rendered, so a single, helpful
    /// warning can be shown once per run instead of one message per diagram (issue #5).
    /// </summary>
    public sealed class DiagramWarningSink
    {
        private readonly HashSet<string> skipped = new(StringComparer.OrdinalIgnoreCase);

        public void NoteSkipped(string diagramTag)
        {
            if (!string.IsNullOrEmpty(diagramTag))
            {
                this.skipped.Add(diagramTag);
            }
        }

        public bool Any => this.skipped.Count > 0;

        public IReadOnlyCollection<string> SkippedTags => this.skipped;
    }

    /// <summary>
    /// Turns a renderer's raw SVG into a self-contained, inline fragment: strips the XML prolog /
    /// <c>&lt;!DOCTYPE&gt;</c> (everything before the first <c>&lt;svg&gt;</c>) and wraps the element in
    /// <c>&lt;figure class="diagram"&gt;</c> so the template can size and print it (issue #5).
    /// </summary>
    public static class SvgInliner
    {
        public static string Wrap(string svg)
        {
            if (svg == null)
            {
                throw new ArgumentNullException(nameof(svg));
            }

            var start = svg.IndexOf("<svg", StringComparison.OrdinalIgnoreCase);
            var body = (start >= 0 ? svg.Substring(start) : svg).Trim();
            return "<figure class=\"diagram\">\n" + body + "\n</figure>\n";
        }
    }

    /// <summary>
    /// Build-time diagram rendering for fenced code blocks: a Markdig extension that swaps in a
    /// code-block renderer intercepting diagram fences (mermaid, plantuml, …) and inlining the SVG a
    /// provider produces. No runtime JS and no CDN — the SVG lives in the page, so the output still
    /// prints and reads offline (issue #5).
    /// </summary>
    /// <remarks>
    /// The renderer <em>decorates</em> the code-block renderer already in place, delegating every
    /// non-diagram block to it. Installed after the syntax highlighter so it wraps (and therefore runs
    /// before) it — diagram fences are never syntax-coloured, everything else still is.
    /// </remarks>
    public sealed class DiagramRenderingExtension : IMarkdownExtension
    {
        private readonly IDiagramProvider provider;
        private readonly DiagramColorScheme scheme;
        private readonly DiagramWarningSink sink;

        public DiagramRenderingExtension(IDiagramProvider provider, DiagramColorScheme scheme, DiagramWarningSink sink)
        {
            this.provider = provider ?? throw new ArgumentNullException(nameof(provider));
            this.scheme = scheme;
            this.sink = sink ?? throw new ArgumentNullException(nameof(sink));
        }

        public void Setup(MarkdownPipelineBuilder pipeline)
        {
            // Rendering concern only; nothing to do at parse time.
        }

        public void Setup(MarkdownPipeline pipeline, IMarkdownRenderer renderer)
        {
            if (renderer is not HtmlRenderer htmlRenderer)
            {
                return;
            }

            // Wrap whatever code-block renderer is present (the stock one, or the highlighter) so its
            // behaviour is preserved for every non-diagram block; fall back to appending if none.
            for (var i = 0; i < htmlRenderer.ObjectRenderers.Count; i++)
            {
                if (htmlRenderer.ObjectRenderers[i] is CodeBlockRenderer inner)
                {
                    htmlRenderer.ObjectRenderers[i] = new DiagramCodeBlockRenderer(inner, this.provider, this.scheme, this.sink);
                    return;
                }
            }

            htmlRenderer.ObjectRenderers.Add(new DiagramCodeBlockRenderer(null, this.provider, this.scheme, this.sink));
        }
    }

    /// <summary>
    /// Renders a fenced block tagged with a diagram language as inline SVG; delegates every other
    /// block to the code-block renderer it decorates. A render that the provider cannot do (or that
    /// fails) is noted for the run's warning and falls back to plain (issue #5).
    /// </summary>
    internal sealed class DiagramCodeBlockRenderer : CodeBlockRenderer
    {
        // Every tag any provider could render — used to recognise a diagram fence regardless of which
        // provider is active, so an unrendered one can be reported even when rendering is off.
        private static readonly HashSet<string> KnownDiagramTags =
            new(DockerDiagramProvider.Tags.Concat(KrokiDiagramProvider.Tags), StringComparer.OrdinalIgnoreCase);

        private readonly CodeBlockRenderer? inner;
        private readonly IDiagramProvider provider;
        private readonly DiagramColorScheme scheme;
        private readonly DiagramWarningSink sink;

        public DiagramCodeBlockRenderer(CodeBlockRenderer? inner, IDiagramProvider provider, DiagramColorScheme scheme, DiagramWarningSink sink)
        {
            this.inner = inner;
            this.provider = provider;
            this.scheme = scheme;
            this.sink = sink;
        }

        protected override void Write(HtmlRenderer renderer, CodeBlock obj)
        {
            if (renderer == null)
            {
                throw new ArgumentNullException(nameof(renderer));
            }

            if (obj is FencedCodeBlock fenced)
            {
                var tag = FirstToken(fenced.Info);
                if (tag != null && KnownDiagramTags.Contains(tag))
                {
                    if (this.provider.CanRender(tag) && this.provider.TryRenderSvg(tag, GetCodeText(fenced), this.scheme, out var svg))
                    {
                        renderer.Write(SvgInliner.Wrap(svg)); // already HTML
                        renderer.EnsureLine();
                        return;
                    }

                    // A diagram we could not render: remember it for the one-shot warning, then let it
                    // fall through to a plain block so the source is still visible.
                    this.sink.NoteSkipped(tag);
                }
            }

            this.WriteInner(renderer, obj);
        }

        // Delegate to the decorated renderer via its public interface (its Write is protected), or to
        // the stock behaviour when there was nothing to wrap.
        private void WriteInner(HtmlRenderer renderer, CodeBlock obj)
        {
            if (this.inner != null)
            {
                ((IMarkdownObjectRenderer)this.inner).Write(renderer, obj);
            }
            else
            {
                base.Write(renderer, obj);
            }
        }

        // The first whitespace-delimited token of the fence info string ("mermaid", "d2 opts" -> "d2");
        // null when there is none.
        private static string? FirstToken(string? info)
        {
            if (string.IsNullOrWhiteSpace(info))
            {
                return null;
            }

            var trimmed = info.TrimStart();
            var space = trimmed.IndexOfAny(new[] { ' ', '\t' });
            return space < 0 ? trimmed : trimmed.Substring(0, space);
        }

        // Joins a code block's raw source lines; the trailing newline is dropped.
        private static string GetCodeText(LeafBlock block)
        {
            var builder = new StringBuilder();
            var lines = block.Lines.Lines;
            var count = block.Lines.Count;
            for (var i = 0; i < count; i++)
            {
                if (i > 0)
                {
                    builder.Append('\n');
                }

                builder.Append(lines[i].Slice.ToString());
            }

            return builder.ToString();
        }
    }

    /// <summary>
    /// Reads a template's declared colour scheme from the standard
    /// <c>&lt;meta name="color-scheme" content="…"&gt;</c> tag (CSS Color Adjustment), used to pick a
    /// matching diagram theme. <c>content</c> is a space-separated ordered list; the first of
    /// <c>light</c>/<c>dark</c> wins (<c>only</c> is ignored). A template with no such tag is treated
    /// as light — so a dark template should declare <c>content="dark"</c>, which also makes the browser
    /// theme its own form controls and scrollbars correctly (issue #5).
    /// </summary>
    public static class TemplateColorScheme
    {
        // Linear patterns (no nested quantifiers), safe against catastrophic backtracking.
        private static readonly Regex MetaTag =
            new Regex(@"<meta\b[^>]*>", RegexOptions.IgnoreCase | RegexOptions.Compiled);

        private static readonly Regex NameIsColorScheme =
            new Regex(@"name\s*=\s*(['""])\s*color-scheme\s*\1", RegexOptions.IgnoreCase | RegexOptions.Compiled);

        private static readonly Regex ContentAttr =
            new Regex(@"content\s*=\s*(['""])(?<value>[^'""]*)\1", RegexOptions.IgnoreCase | RegexOptions.Compiled);

        private static readonly char[] Whitespace = { ' ', '\t', '\r', '\n', };

        public static DiagramColorScheme Resolve(string? template)
        {
            if (string.IsNullOrEmpty(template))
            {
                return DiagramColorScheme.Light;
            }

            foreach (Match meta in MetaTag.Matches(template))
            {
                if (!NameIsColorScheme.IsMatch(meta.Value))
                {
                    continue;
                }

                var content = ContentAttr.Match(meta.Value);
                if (!content.Success)
                {
                    continue;
                }

                foreach (var token in content.Groups["value"].Value.Split(Whitespace, StringSplitOptions.RemoveEmptyEntries))
                {
                    if ("only".Equals(token, StringComparison.OrdinalIgnoreCase))
                    {
                        continue;
                    }

                    if ("dark".Equals(token, StringComparison.OrdinalIgnoreCase))
                    {
                        return DiagramColorScheme.Dark;
                    }

                    if ("light".Equals(token, StringComparison.OrdinalIgnoreCase))
                    {
                        return DiagramColorScheme.Light;
                    }
                }
            }

            return DiagramColorScheme.Light;
        }
    }

    /// <summary>
    /// Creates the <see cref="IDiagramProvider"/> for a run from its selected kind. The optional
    /// <paramref name="log"/> receives a reason whenever a render is skipped (wired to --verbose).
    /// </summary>
    public static class DiagramProviderFactory
    {
        public static IDiagramProvider Create(DiagramProviderKind kind, string? krokiUrl, Action<string>? log = null)
        {
            switch (kind)
            {
                case DiagramProviderKind.Docker:
                    return new DockerDiagramProvider(log);
                case DiagramProviderKind.Kroki:
                    return new KrokiDiagramProvider(krokiUrl!, log);
                default:
                    return new NoneDiagramProvider();
            }
        }
    }
}
