// Generated by Claude Opus 4.8 (claude.ai/code) · 2026-09-24
namespace Airudit.MdBook.Core
{
    using System;
    using System.Collections.Generic;

    /// <summary>
    /// The project-local doc manifest parsed from a <c>.mdbook[.lang].md</c> file's front-matter
    /// (issue #30): which pages lead the book (<see cref="Priority"/>), which are dropped
    /// (<see cref="Exclude"/>), and how the combined single-file table of contents is presented.
    /// Every key is optional; an absent manifest is equivalent to an all-default one. Path entries
    /// (in <see cref="Priority"/> and <see cref="Exclude"/>) resolve relative to the
    /// <c>.mdbook</c> file's own directory, not the working directory.
    /// </summary>
    internal sealed class DocManifest
    {
        /// <summary>Featured pages, in listed order, rendered as the "Start here" table-of-contents band (single-file only).</summary>
        public IReadOnlyList<string> Priority { get; private set; } = Array.Empty<string>();

        /// <summary>Pages removed from the book — files, directories (trailing <c>/</c>) or globs. Acts in every output mode.</summary>
        public IReadOnlyList<string> Exclude { get; private set; } = Array.Empty<string>();

        /// <summary>When true, ship only the <see cref="Priority"/> pages and drop everything else (single-file only). Default false.</summary>
        public bool Exclusive { get; private set; }

        /// <summary>When false, suppress the generated table of contents so the author's intro is the index (single-file only). Default true.</summary>
        public bool Toc { get; private set; } = true;

        /// <summary>Heading for the "Start here" priority band; null falls back to a localized default.</summary>
        public string? PriorityTitle { get; private set; }

        /// <summary>Heading for the generated table of contents; null falls back to a localized default.</summary>
        public string? TocTitle { get; private set; }

        /// <summary>Reads a manifest from an already-parsed front-matter block. Unknown keys are ignored (forward-compatible).</summary>
        public static DocManifest FromFrontMatter(FrontMatter frontMatter)
        {
            if (frontMatter == null)
            {
                throw new ArgumentNullException(nameof(frontMatter));
            }

            return new DocManifest
            {
                Priority = frontMatter.GetList("priority"),
                Exclude = frontMatter.GetList("exclude"),
                Exclusive = frontMatter.GetBool("exclusive") ?? false,
                Toc = frontMatter.GetBool("toc") ?? true,
                PriorityTitle = frontMatter.GetString("priority-title"),
                TocTitle = frontMatter.GetString("toc-title"),
            };
        }
    }
}
