// Generated by Claude Opus 4.8 (claude.ai/code) · 2026-09-24
namespace Airudit.MdBook.Core
{
    using Markdig.Extensions.Yaml;
    using Markdig.Syntax;
    using System;
    using System.Collections.Generic;
    using System.Globalization;
    using System.Text;

    /// <summary>
    /// A minimal reader for a document's top-of-file YAML front-matter, covering the small, flat
    /// subset mdbook needs — scalars, flow (<c>[a, b]</c>) and block (<c>- a</c>) sequences,
    /// booleans and integers — with no YAML-library dependency (issues #29, #30). Nested maps,
    /// anchors, tags and multiline scalars are intentionally unsupported: keys that use them are
    /// ignored rather than parsed.
    /// </summary>
    internal sealed class FrontMatter
    {
        private readonly Dictionary<string, string?> scalars;
        private readonly Dictionary<string, List<string>> lists;

        private FrontMatter(Dictionary<string, string?> scalars, Dictionary<string, List<string>> lists)
        {
            this.scalars = scalars;
            this.lists = lists;
        }

        /// <summary>An empty front-matter with no keys, returned for a document that has no front-matter block.</summary>
        public static FrontMatter Empty { get; } = new FrontMatter(
            new Dictionary<string, string?>(StringComparer.Ordinal),
            new Dictionary<string, List<string>>(StringComparer.Ordinal));

        /// <summary>
        /// Reads the YAML front-matter block at the very start of a parsed document, or
        /// <see cref="Empty"/> when the document has none. Front-matter is only ever the document's
        /// first block, so an included partial's own front-matter is never read here.
        /// </summary>
        public static FrontMatter FromDocument(MarkdownDocument dom)
        {
            if (dom == null || dom.Count == 0 || dom[0] is not YamlFrontMatterBlock yaml)
            {
                return Empty;
            }

            var text = new StringBuilder();
            var lines = yaml.Lines.Lines;
            for (var i = 0; i < yaml.Lines.Count; i++)
            {
                text.Append(lines[i].Slice.ToString());
                text.Append('\n');
            }

            return Parse(text.ToString());
        }

        /// <summary>
        /// Parses raw front-matter text — the lines between the <c>---</c> fences, the fences
        /// themselves excluded (a stray fence line is tolerated and ignored). Top-level keys are
        /// unindented; indented lines are treated as sequence items of the key above or otherwise
        /// skipped.
        /// </summary>
        public static FrontMatter Parse(string? text)
        {
            var scalars = new Dictionary<string, string?>(StringComparer.Ordinal);
            var lists = new Dictionary<string, List<string>>(StringComparer.Ordinal);
            if (string.IsNullOrEmpty(text))
            {
                return new FrontMatter(scalars, lists);
            }

            var lines = text.Replace("\r\n", "\n").Replace('\r', '\n').Split('\n');
            var i = 0;
            while (i < lines.Length)
            {
                var line = lines[i];
                var trimmed = line.Trim();

                // Skip blank lines, full-line comments, and stray indented lines (a nested map we
                // do not support, or a sequence item already consumed by the key above).
                if (trimmed.Length == 0 || trimmed[0] == '#' || char.IsWhiteSpace(line[0]))
                {
                    i++;
                    continue;
                }

                var colon = line.IndexOf(':');
                if (colon <= 0)
                {
                    // Not a "key: value" mapping (e.g. a stray "---" fence or a top-level dash).
                    i++;
                    continue;
                }

                var key = line.Substring(0, colon).Trim();
                var rest = line.Substring(colon + 1).Trim();

                if (rest.Length == 0)
                {
                    // A bare "key:" opens either a block sequence (following "- item" lines) or,
                    // when none follow, an empty scalar.
                    var items = new List<string>();
                    var j = i + 1;
                    for (; j < lines.Length; j++)
                    {
                        var itemLine = lines[j].Trim();
                        if (itemLine.Length == 0)
                        {
                            break;
                        }

                        if (!(itemLine == "-" || itemLine.StartsWith("- ", StringComparison.Ordinal)))
                        {
                            break;
                        }

                        var itemValue = itemLine.Length == 1 ? string.Empty : itemLine.Substring(2);
                        var cleaned = CleanScalar(itemValue);
                        if (cleaned.Length > 0)
                        {
                            items.Add(cleaned);
                        }
                    }

                    if (j > i + 1)
                    {
                        lists[key] = items;
                        i = j;
                    }
                    else
                    {
                        scalars[key] = null;
                        i++;
                    }

                    continue;
                }

                if (rest[0] == '[')
                {
                    lists[key] = ParseFlowList(rest);
                    i++;
                    continue;
                }

                var scalar = CleanScalar(rest);
                scalars[key] = scalar.Length > 0 ? scalar : null;
                i++;
            }

            return new FrontMatter(scalars, lists);
        }

        /// <summary>The value of a scalar key, or null when the key is absent or its value is empty.</summary>
        public string? GetString(string key)
        {
            return this.scalars.TryGetValue(key, out var value) ? value : null;
        }

        /// <summary>
        /// The items of a sequence key. A key written as a single scalar yields a one-item list;
        /// an absent or empty key yields an empty list (never null).
        /// </summary>
        public IReadOnlyList<string> GetList(string key)
        {
            if (this.lists.TryGetValue(key, out var list))
            {
                return list;
            }

            if (this.scalars.TryGetValue(key, out var scalar) && !string.IsNullOrEmpty(scalar))
            {
                return new[] { scalar };
            }

            return Array.Empty<string>();
        }

        /// <summary>A boolean scalar (<c>true/false</c>, <c>yes/no</c>, <c>on/off</c>, <c>1/0</c>), or null when absent or unrecognised.</summary>
        public bool? GetBool(string key)
        {
            var value = this.GetString(key);
            if (value == null)
            {
                return null;
            }

            switch (value.Trim().ToLowerInvariant())
            {
                case "true":
                case "yes":
                case "on":
                case "1":
                    return true;
                case "false":
                case "no":
                case "off":
                case "0":
                    return false;
                default:
                    return null;
            }
        }

        /// <summary>An integer scalar, or null when the key is absent or its value is not an integer.</summary>
        public int? GetInt(string key)
        {
            var value = this.GetString(key);
            if (value != null && int.TryParse(value.Trim(), NumberStyles.Integer, CultureInfo.InvariantCulture, out var number))
            {
                return number;
            }

            return null;
        }

        // Splits a flow sequence ("[a, b, c]") into cleaned items; anything outside the outermost
        // brackets is ignored. An empty or malformed list yields no items.
        private static List<string> ParseFlowList(string rest)
        {
            var result = new List<string>();
            var open = rest.IndexOf('[');
            var close = rest.LastIndexOf(']');
            if (open < 0 || close <= open)
            {
                return result;
            }

            var inner = rest.Substring(open + 1, close - open - 1);
            foreach (var part in inner.Split(','))
            {
                var cleaned = CleanScalar(part);
                if (cleaned.Length > 0)
                {
                    result.Add(cleaned);
                }
            }

            return result;
        }

        // Trims a scalar, strips one layer of matching quotes (a quoted value is taken verbatim),
        // otherwise drops an inline "# comment" (a hash preceded by whitespace, per YAML).
        private static string CleanScalar(string value)
        {
            value = value.Trim();
            if (value.Length >= 2 && (value[0] == '"' || value[0] == '\'') && value[^1] == value[0])
            {
                return value.Substring(1, value.Length - 2);
            }

            for (var k = 1; k < value.Length; k++)
            {
                if (value[k] == '#' && char.IsWhiteSpace(value[k - 1]))
                {
                    return value.Substring(0, k).TrimEnd();
                }
            }

            return value;
        }
    }
}
