// Generated by Claude Opus 4.8 (claude.ai/code) · 2026-09-24
namespace Airudit.MdBook.Core
{
    using System;
    using System.Collections.Generic;
    using System.Globalization;
    using System.Text.RegularExpressions;

    /// <summary>
    /// Matches a doc-manifest path entry (from <c>exclude</c> or <c>priority</c>) against a page,
    /// where the page's path is expressed relative to the <c>.mdbook</c> file's own directory
    /// (issue #30). All paths use <c>/</c> separators and match case-insensitively.
    /// </summary>
    internal static class ManifestMatcher
    {
        /// <summary>
        /// Whether <paramref name="entry"/> matches a page at <paramref name="relativePath"/>:
        /// <list type="bullet">
        /// <item>a trailing <c>/</c> matches a directory and its whole subtree;</item>
        /// <item>a <c>*</c> is a glob within a single path segment (it does not cross <c>/</c>);</item>
        /// <item>otherwise a file path, where the trailing <c>.md</c> and an optional language
        /// segment (e.g. <c>.en-US</c>) are optional on both sides.</item>
        /// </list>
        /// </summary>
        public static bool Matches(string entry, string relativePath)
        {
            if (string.IsNullOrEmpty(entry) || string.IsNullOrEmpty(relativePath))
            {
                return false;
            }

            entry = entry.Replace('\\', '/').Trim();
            relativePath = relativePath.Replace('\\', '/');

            if (entry.EndsWith("/", StringComparison.Ordinal))
            {
                return relativePath.StartsWith(entry, StringComparison.OrdinalIgnoreCase);
            }

            if (entry.IndexOf('*') >= 0)
            {
                var pattern = "^" + Regex.Escape(entry).Replace("\\*", "[^/]*") + "$";
                return Regex.IsMatch(relativePath, pattern, RegexOptions.IgnoreCase);
            }

            var candidates = PathCandidates(relativePath);
            return candidates.Contains(entry) || candidates.Contains(StripMarkdownExtension(entry));
        }

        // The forms a page path can be addressed by: the full path, without its ".md" extension,
        // and without both the extension and a trailing language segment.
        private static HashSet<string> PathCandidates(string relativePath)
        {
            var noExtension = StripMarkdownExtension(relativePath);
            return new HashSet<string>(StringComparer.OrdinalIgnoreCase)
            {
                relativePath,
                noExtension,
                StripLanguageSegment(noExtension),
            };
        }

        // Drops a trailing ".md" (case-insensitive), leaving any other value untouched.
        private static string StripMarkdownExtension(string path)
        {
            return path.EndsWith(".md", StringComparison.OrdinalIgnoreCase)
                ? path.Substring(0, path.Length - ".md".Length)
                : path;
        }

        // Drops a trailing ".<lang>" segment from the file name when it parses as a culture
        // (e.g. "guide/how.en-US" -> "guide/how"), mirroring the file-name language detection.
        private static string StripLanguageSegment(string path)
        {
            var slash = path.LastIndexOf('/');
            var directory = slash >= 0 ? path.Substring(0, slash + 1) : string.Empty;
            var name = slash >= 0 ? path.Substring(slash + 1) : path;

            var dot = name.LastIndexOf('.');
            if (dot <= 0 || name.Length - dot - 1 < 2)
            {
                return path;
            }

            var candidate = name.Substring(dot + 1);
            try
            {
                _ = new CultureInfo(candidate);
                return directory + name.Substring(0, dot);
            }
            catch (CultureNotFoundException)
            {
                return path;
            }
        }
    }
}
