// Generated by Claude Opus 4.8 (claude.ai/code) · 2026-09-14
namespace Airudit.MdBook.Core
{
    using Markdig.Syntax;
    using Markdig.Syntax.Inlines;
    using System;
    using System.Collections.Generic;
    using System.IO;
    using System.Linq;

    /// <summary>
    /// Makes a rendered book self-contained by inlining local images referenced by
    /// <c>![alt](path)</c> as <c>data:</c> URIs, so the HTML keeps displaying them once moved
    /// away from its source folder (issues #13 and #21).
    /// </summary>
    /// <remarks>
    /// A discrete, replaceable rendering stage built on Markdig's own URL hook
    /// (<see cref="LinkInline.GetDynamicUrl"/>): the image node keeps its <c>alt</c>/<c>title</c>
    /// and Markdig still writes the <c>&lt;img&gt;</c> — only its <c>src</c> becomes the data URI.
    /// Called per file, where the base directory is known, rather than from the shared pipeline.
    /// </remarks>
    public static class SelfContainedImageEmbedder
    {
        // Media type by file extension: only a labelling fallback when content sniffing is
        // inconclusive (a data: URI must carry a media type; the browser will not sniff one).
        private static readonly Dictionary<string, string> mediaTypeByExtension = new(StringComparer.OrdinalIgnoreCase)
        {
            [".png"] = "image/png",
            [".jpg"] = "image/jpeg",
            [".jpeg"] = "image/jpeg",
            [".gif"] = "image/gif",
            [".webp"] = "image/webp",
            [".bmp"] = "image/bmp",
            [".ico"] = "image/x-icon",
            [".svg"] = "image/svg+xml",
            [".avif"] = "image/avif",
            [".apng"] = "image/apng",
            [".tif"] = "image/tiff",
            [".tiff"] = "image/tiff",
        };

        /// <summary>
        /// Walks every image in <paramref name="document"/> and inlines the ones pointing at a
        /// readable local file as a <c>data:</c> URI. Remote (absolute), already-inlined
        /// (<c>data:</c>) and missing images are left untouched. Returns how many were inlined.
        /// </summary>
        /// <param name="document">The assembled page document to rewrite.</param>
        /// <param name="baseDirectory">Directory the image paths resolve against (the page's folder).</param>
        /// <param name="warn">Optional sink for a note about each skipped local image (e.g. missing file).</param>
        public static int EmbedImages(MarkdownDocument document, string baseDirectory, Action<string>? warn = null)
        {
            if (document == null)
            {
                throw new ArgumentNullException(nameof(document));
            }

            if (baseDirectory == null)
            {
                throw new ArgumentNullException(nameof(baseDirectory));
            }

            var embedded = 0;
            foreach (var image in document.Descendants().OfType<LinkInline>())
            {
                if (!image.IsImage)
                {
                    continue;
                }

                var url = image.Url;
                if (string.IsNullOrEmpty(url)
                    || url.StartsWith("data:", StringComparison.OrdinalIgnoreCase)
                    || url.StartsWith("//", StringComparison.Ordinal)
                    || Uri.IsWellFormedUriString(url, UriKind.Absolute))
                {
                    // Remote or already-inlined: nothing local to embed.
                    continue;
                }

                // Drop any trailing #fragment and decode %-escapes to reach the file on disk.
                var fragment = url.IndexOf('#');
                var relativePath = fragment >= 0 ? url.Substring(0, fragment) : url;
                relativePath = Uri.UnescapeDataString(relativePath);

                string fullPath;
                try
                {
                    fullPath = Path.Combine(baseDirectory, relativePath);
                }
                catch (ArgumentException)
                {
                    // Illegal characters in the path: leave the reference as authored.
                    continue;
                }

                if (!File.Exists(fullPath))
                {
                    warn?.Invoke("Cannot embed image \"" + url + "\": file not found. Left as a reference. ");
                    continue;
                }

                byte[] bytes;
                try
                {
                    bytes = File.ReadAllBytes(fullPath);
                }
                catch (IOException ex)
                {
                    warn?.Invoke("Cannot embed image \"" + url + "\": " + ex.Message + " Left as a reference. ");
                    continue;
                }
                catch (UnauthorizedAccessException ex)
                {
                    warn?.Invoke("Cannot embed image \"" + url + "\": " + ex.Message + " Left as a reference. ");
                    continue;
                }

                var mediaType = DetectMediaType(bytes, fullPath);
                var dataUri = "data:" + mediaType + ";base64," + Convert.ToBase64String(bytes);

                // Markdig's HTML renderer honours GetDynamicUrl in place of Url, so the <img> is
                // still rendered normally (alt, title) with the data URI as its src.
                image.GetDynamicUrl = () => dataUri;
                embedded++;
            }

            return embedded;
        }

        /// <summary>
        /// Determines an image's media type from its content (magic bytes), falling back to the
        /// file extension, then to <c>application/octet-stream</c>. Detection only labels the data
        /// URI — whether to embed is decided by the <c>&lt;img&gt;</c> element, not by a format list.
        /// </summary>
        internal static string DetectMediaType(byte[] bytes, string path)
        {
            if (bytes != null)
            {
                if (StartsWith(bytes, 0x89, 0x50, 0x4E, 0x47, 0x0D, 0x0A, 0x1A, 0x0A))
                {
                    return "image/png";
                }

                if (StartsWith(bytes, 0xFF, 0xD8, 0xFF))
                {
                    return "image/jpeg";
                }

                if (StartsWith(bytes, 0x47, 0x49, 0x46, 0x38))
                {
                    // "GIF8"
                    return "image/gif";
                }

                if (StartsWith(bytes, 0x42, 0x4D))
                {
                    // "BM"
                    return "image/bmp";
                }

                if (StartsWith(bytes, 0x00, 0x00, 0x01, 0x00))
                {
                    return "image/x-icon";
                }

                // "RIFF" .... "WEBP"
                if (bytes.Length >= 12
                    && StartsWith(bytes, 0x52, 0x49, 0x46, 0x46)
                    && bytes[8] == 0x57 && bytes[9] == 0x45 && bytes[10] == 0x42 && bytes[11] == 0x50)
                {
                    return "image/webp";
                }

                // ISO-BMFF "ftyp" box (offset 4) covers AVIF/HEIF.
                if (bytes.Length >= 12 && bytes[4] == 0x66 && bytes[5] == 0x74 && bytes[6] == 0x79 && bytes[7] == 0x70)
                {
                    if (bytes[8] == 0x61 && bytes[9] == 0x76 && bytes[10] == 0x69 && bytes[11] == 0x66)
                    {
                        // "avif"
                        return "image/avif";
                    }

                    if (bytes[8] == 0x68 && bytes[9] == 0x65 && bytes[10] == 0x69 && bytes[11] == 0x63)
                    {
                        // "heic"
                        return "image/heic";
                    }
                }

                if (LooksLikeSvg(bytes))
                {
                    return "image/svg+xml";
                }
            }

            var extension = Path.GetExtension(path);
            if (!string.IsNullOrEmpty(extension) && mediaTypeByExtension.TryGetValue(extension, out var byExtension))
            {
                return byExtension;
            }

            return "application/octet-stream";
        }

        // True when the bytes begin with the given signature.
        private static bool StartsWith(byte[] bytes, params byte[] signature)
        {
            if (bytes.Length < signature.Length)
            {
                return false;
            }

            for (var i = 0; i < signature.Length; i++)
            {
                if (bytes[i] != signature[i])
                {
                    return false;
                }
            }

            return true;
        }

        // SVG is text, so sniff for an "<svg" tag near the start, past an optional BOM,
        // XML declaration, or DOCTYPE. Scans a small window only.
        private static bool LooksLikeSvg(byte[] bytes)
        {
            var start = 0;
            if (bytes.Length >= 3 && bytes[0] == 0xEF && bytes[1] == 0xBB && bytes[2] == 0xBF)
            {
                start = 3; // UTF-8 BOM
            }

            var window = Math.Min(bytes.Length, start + 1024);
            for (var i = start; i + 4 <= window; i++)
            {
                if (bytes[i] == (byte)'<'
                    && (bytes[i + 1] == (byte)'s' || bytes[i + 1] == (byte)'S')
                    && (bytes[i + 2] == (byte)'v' || bytes[i + 2] == (byte)'V')
                    && (bytes[i + 3] == (byte)'g' || bytes[i + 3] == (byte)'G'))
                {
                    return true;
                }
            }

            return false;
        }
    }
}
