// Generated by Claude Opus 4.8 (claude.ai/code) · 2026-09-28
//
// Derived from ColorCode-Universal's Compilation/Languages/Json.cs (only Regex_String changed).
// Licensed to the .NET Foundation under one or more agreements.
// The .NET Foundation licenses this file to you under the MIT license.
// See https://github.com/CommunityToolkit/ColorCode-Universal for the original source and LICENSE.
namespace Airudit.MdBook.Core
{
    using ColorCode;
    using ColorCode.Common;
    using System.Collections.Generic;

    /// <summary>
    /// A drop-in replacement for ColorCode's built-in JSON grammar that fixes catastrophic regex
    /// backtracking (CommunityToolkit/ColorCode-Universal#45, #36). The shipped NuGet 2.0.15 string
    /// pattern <c>"[^"\\]*(?:\\[^\r\n]|[^"\\]*)*"</c> has an empty-matchable alternative under a
    /// quantifier (Friedl's shape), so a JSON array of long string values drives the key rule into
    /// O(2^n) backtracking and pins the CPU. This uses Friedl's unrolled loop
    /// <c>"[^"\\]*(?:\\.[^"\\]*)*"</c> — linear time, identical matches for valid JSON. It is loaded
    /// over the built-in "json" id via <see cref="Languages.Load(ILanguage)"/> at pipeline setup.
    /// </summary>
    /// <remarks>
    /// TEMPORARY: remove this class and <c>SyntaxHighlightingExtension.InstallLanguageOverrides</c>
    /// once the fix ships in a ColorCode.HTML release and the package reference is bumped (upstream
    /// PR CommunityToolkit/ColorCode-Universal#46). The rules mirror the built-in grammar exactly
    /// except for <see cref="Regex_String"/>.
    /// </remarks>
    internal sealed class FixedJsonLanguage : ILanguage
    {
        private const string Regex_String = @"""[^""\\]*(?:\\.[^""\\]*)*""";
        private const string Regex_Number = @"-?(?:0|[1-9][0-9]*)(?:\.[0-9]*)?(?:[eE][-+]?[0-9]+)?";

        public string Id
        {
            get { return LanguageId.Json; }
        }

        public string Name
        {
            get { return "JSON"; }
        }

        public string CssClassName
        {
            get { return "json"; }
        }

        public string FirstLinePattern
        {
            get { return null; }
        }

        public IList<LanguageRule> Rules
        {
            get
            {
                return new List<LanguageRule>
                           {
                               new LanguageRule(
                                   $@"[,\{{]\s*({Regex_String})\s*:",
                                   new Dictionary<int, string>
                                       {
                                           {1, ScopeName.JsonKey}
                                       }),
                               new LanguageRule(
                                   Regex_String,
                                   new Dictionary<int, string>
                                       {
                                           {0, ScopeName.JsonString}
                                       }),
                               new LanguageRule(
                                   Regex_Number,
                                   new Dictionary<int, string>
                                       {
                                           {0, ScopeName.JsonNumber}
                                       }),
                               new LanguageRule(
                                   @"\b(true|false|null)\b",
                                   new Dictionary<int, string>
                                       {
                                           {1, ScopeName.JsonConst}
                                       }),
                           };
            }
        }

        public bool HasAlias(string lang)
        {
            return false;
        }
    }
}
