// Generated by Claude Opus 4.8 (claude.ai/code) · 2026-09-14
namespace Airudit.MdBook.Core
{
    using ColorCode;
    using ColorCode.Styling;
    using Markdig;
    using Markdig.Renderers;
    using Markdig.Renderers.Html;
    using Markdig.Syntax;
    using System;
    using System.Collections.Generic;
    using System.Linq;
    using System.Text;
    using System.Text.RegularExpressions;

    /// <summary>
    /// Build-time syntax highlighting for fenced code blocks: a Markdig extension that swaps in a
    /// code-block renderer which tokenises a recognised language into classed <c>&lt;span&gt;</c>s
    /// (via ColorCode). No JavaScript and no network — the colours live in the template's
    /// <c>&lt;style&gt;</c>, so the output still prints and reads in a terminal browser (issue #25).
    /// </summary>
    /// <remarks>
    /// Blocks with no language, or a language ColorCode does not know, render exactly as before.
    /// Added to the pipeline only when highlighting is enabled, so it is a discrete, removable stage.
    /// </remarks>
    public sealed class SyntaxHighlightingExtension : IMarkdownExtension
    {
        public void Setup(MarkdownPipelineBuilder pipeline)
        {
            // Highlighting is a rendering concern only; nothing to do at parse time.
        }

        // ColorCode's grammar regexes carry no match timeout, so malformed input (commented,
        // truncated or unterminated JSON) can send them into catastrophic backtracking for minutes.
        // Install a process-wide default timeout for timeout-less regexes so such a match aborts and
        // the block falls back to plain text (issue #25). Must run before any highlighting — call it
        // during pipeline construction, not lazily, or ColorCode compiles its regexes without it.
        public static void InstallDefaultRegexTimeout()
        {
            if (AppDomain.CurrentDomain.GetData("REGEX_DEFAULT_MATCH_TIMEOUT") == null)
            {
                AppDomain.CurrentDomain.SetData("REGEX_DEFAULT_MATCH_TIMEOUT", ResolveMatchTimeout());
            }
        }

        // The per-block match timeout: MDBOOK_HIGHLIGHT_TIMEOUT_MS if a positive integer, else 1000 ms.
        public static TimeSpan ResolveMatchTimeout()
        {
            const int defaultMs = 1000;
            var raw = Environment.GetEnvironmentVariable("MDBOOK_HIGHLIGHT_TIMEOUT_MS");
            if (int.TryParse(raw, out var ms) && ms > 0)
            {
                return TimeSpan.FromMilliseconds(ms);
            }

            return TimeSpan.FromMilliseconds(defaultMs);
        }

        public void Setup(MarkdownPipeline pipeline, IMarkdownRenderer renderer)
        {
            if (renderer is not HtmlRenderer htmlRenderer)
            {
                return;
            }

            // Replace Markdig's default code-block renderer in place, preserving order so other
            // renderers are unaffected. Fall back to appending if none is present.
            for (var i = 0; i < htmlRenderer.ObjectRenderers.Count; i++)
            {
                if (htmlRenderer.ObjectRenderers[i] is CodeBlockRenderer)
                {
                    htmlRenderer.ObjectRenderers[i] = new HighlightingCodeBlockRenderer();
                    return;
                }
            }

            htmlRenderer.ObjectRenderers.Add(new HighlightingCodeBlockRenderer());
        }
    }

    /// <summary>
    /// Renders a fenced code block with a recognised language as highlighted token spans; delegates
    /// every other code block to the stock <see cref="CodeBlockRenderer"/> so plain and indented
    /// blocks are untouched.
    /// </summary>
    internal sealed class HighlightingCodeBlockRenderer : CodeBlockRenderer
    {
        private static readonly HtmlClassFormatter formatter = new HtmlClassFormatter();

        // Common Markdown fence tags mapped to ColorCode language ids where they differ.
        private static readonly Dictionary<string, string> languageAliases = new(StringComparer.OrdinalIgnoreCase)
        {
            ["cs"] = "csharp",
            ["c#"] = "csharp",
            ["js"] = "javascript",
            ["ts"] = "typescript",
            ["ps"] = "powershell",
            ["ps1"] = "powershell",
            ["posh"] = "powershell",
            ["htm"] = "html",
            ["f#"] = "fsharp",
            ["fs"] = "fsharp",
            ["c++"] = "cpp",
            ["cc"] = "cpp",
            ["md"] = "markdown",
            ["vb"] = "vbdotnet",
        };

        protected override void Write(HtmlRenderer renderer, CodeBlock obj)
        {
            if (renderer == null)
            {
                throw new ArgumentNullException(nameof(renderer));
            }

            if (obj is FencedCodeBlock fenced)
            {
                var languageId = FirstToken(fenced.Info);
                var language = ResolveLanguage(languageId);
                if (language != null && TryHighlight(GetCodeText(fenced), language, out var inner))
                {
                    renderer.Write("<pre><code class=\"language-");
                    renderer.WriteEscape(languageId);
                    renderer.Write("\">");
                    renderer.Write(inner); // already HTML (ColorCode escapes the code text)
                    renderer.Write("</code></pre>");
                    renderer.EnsureLine();
                    return;
                }
            }

            base.Write(renderer, obj);
        }

        // The first whitespace-delimited token of the fence info string is the language
        // ("csharp", "cs {highlight}" -> "cs"); returns null when there is none.
        private static string? FirstToken(string? info)
        {
            if (string.IsNullOrWhiteSpace(info))
            {
                return null;
            }

            var trimmed = info.TrimStart();
            var space = trimmed.IndexOfAny(new[] { ' ', '\t' });
            return space < 0 ? trimmed : trimmed.Substring(0, space);
        }

        // Resolves a fence tag to a ColorCode language, applying the alias table first. Returns
        // null for an unknown or absent tag, which leaves the block rendered as plain code.
        private static ILanguage? ResolveLanguage(string? languageId)
        {
            if (string.IsNullOrEmpty(languageId))
            {
                return null;
            }

            var id = languageAliases.TryGetValue(languageId, out var mapped) ? mapped : languageId;
            return Languages.FindById(id);
        }

        // Attempts to highlight a block, returning false so the caller renders it plain when the
        // grammar times out on pathological input (issue #25) or ColorCode throws for any reason —
        // highlighting is best-effort decoration and must never fail or stall a render.
        private static bool TryHighlight(string code, ILanguage language, out string inner)
        {
            try
            {
                inner = HighlightToInnerHtml(code, language);
                return true;
            }
            catch (RegexMatchTimeoutException)
            {
                inner = string.Empty;
                return false;
            }
            catch (Exception)
            {
                inner = string.Empty;
                return false;
            }
        }

        // Runs ColorCode and returns just the inner token markup, dropping the
        // "<div class="lang"><pre> ... </pre></div>" wrapper it adds — mdbook keeps its own
        // <pre><code> wrapper so the output stays consistent with unhighlighted blocks.
        private static string HighlightToInnerHtml(string code, ILanguage language)
        {
            var html = formatter.GetHtmlString(code, language);

            const string openPre = "<pre>";
            const string closePre = "</pre>";
            var start = html.IndexOf(openPre, StringComparison.Ordinal);
            var end = html.LastIndexOf(closePre, StringComparison.Ordinal);
            if (start < 0 || end < 0 || end < start)
            {
                return html;
            }

            start += openPre.Length;
            var inner = html.Substring(start, end - start);

            // ColorCode puts a newline right after <pre> and before </pre>; trim one of each so the
            // rendered block does not gain blank leading/trailing lines.
            inner = TrimOneNewline(inner, leading: true);
            inner = TrimOneNewline(inner, leading: false);
            return inner;
        }

        private static string TrimOneNewline(string value, bool leading)
        {
            if (leading)
            {
                if (value.StartsWith("\r\n", StringComparison.Ordinal))
                {
                    return value.Substring(2);
                }

                return value.Length > 0 && value[0] == '\n' ? value.Substring(1) : value;
            }

            if (value.EndsWith("\r\n", StringComparison.Ordinal))
            {
                return value.Substring(0, value.Length - 2);
            }

            return value.Length > 0 && value[^1] == '\n' ? value.Substring(0, value.Length - 1) : value;
        }

        // Joins a code block's raw source lines. The trailing newline that closes the last line is
        // dropped so ColorCode does not see a spurious empty final line.
        private static string GetCodeText(LeafBlock block)
        {
            var builder = new StringBuilder();
            var lines = block.Lines.Lines;
            var count = block.Lines.Count;
            for (var i = 0; i < count; i++)
            {
                if (i > 0)
                {
                    builder.Append('\n');
                }

                builder.Append(lines[i].Slice.ToString());
            }

            return builder.ToString();
        }
    }

    /// <summary>
    /// Produces the CSS that colours the highlighter's token classes, generated at render time from
    /// ColorCode's built-in themes — so no third-party colours are copied into the templates — and
    /// substituted into a template's <c>{{{HighlightStyles}}}</c> (light) or
    /// <c>{{{HighlightStyles.dark}}}</c> (dark) placeholder. Scoped to <c>pre code</c>; cached per
    /// theme (issue #25).
    /// </summary>
    public static class HighlightStylesheet
    {
        private const string LightKey = "HighlightStyles";
        private const string DarkKey = "HighlightStyles.dark";
        private static string? lightCss;
        private static string? darkCss;

        /// <summary>True when <paramref name="placeholderKey"/> is a highlight-styles placeholder.</summary>
        public static bool IsPlaceholder(string placeholderKey)
        {
            return placeholderKey is LightKey or DarkKey;
        }

        /// <summary>
        /// The CSS for a highlight-styles placeholder, or an empty string when highlighting is off
        /// (the token spans are then absent, so no colours are needed).
        /// </summary>
        public static string Render(string placeholderKey, bool highlightingEnabled)
        {
            if (!highlightingEnabled)
            {
                return string.Empty;
            }

            return placeholderKey == DarkKey
                ? darkCss ??= Build(StyleDictionary.DefaultDark)
                : lightCss ??= Build(StyleDictionary.DefaultLight);
        }

        // Turns a ColorCode theme into scoped, de-duplicated CSS: one rule per colour, each token
        // class prefixed with "pre code" so only fenced blocks are affected. The base text colour
        // comes from the theme's Plain Text entry, so mdbook does not hard-code it either.
        private static string Build(StyleDictionary theme)
        {
            var raw = new HtmlClassFormatter(theme).GetCSSString();

            var baseColor = "#000000";
            var plain = Regex.Match(raw, @"\.plainText\{color:([^;}]+)");
            if (plain.Success)
            {
                baseColor = ToHexColor(plain.Groups[1].Value) ?? baseColor;
            }

            var classesByColor = new Dictionary<string, List<string>>(StringComparer.Ordinal);
            var colorOrder = new List<string>();
            foreach (Match rule in Regex.Matches(raw, @"\.(\w+)\{color:([^;}]+)"))
            {
                var className = rule.Groups[1].Value;
                if (className == "plainText")
                {
                    continue;
                }

                var color = ToHexColor(rule.Groups[2].Value);
                if (color == null || color == baseColor)
                {
                    continue;
                }

                if (!classesByColor.TryGetValue(color, out var list))
                {
                    list = new List<string>();
                    classesByColor[color] = list;
                    colorOrder.Add(color);
                }

                list.Add(className);
            }

            var builder = new StringBuilder();
            builder.Append("    /* Syntax highlighting theme derived from ColorCode (MIT). See issue #25. */\n");
            builder.Append("    pre code { color: ").Append(baseColor).Append("; }\n");
            foreach (var color in colorOrder)
            {
                var selector = string.Join(", ", classesByColor[color].Select(name => "pre code ." + name));
                builder.Append("    ").Append(selector).Append(" { color: ").Append(color).Append("; }\n");
            }

            return builder.ToString().TrimEnd('\n');
        }

        // Normalises a ColorCode colour (ARGB like "#FF0000FF", or malformed "#FF#E6E6E6") to a
        // 6-digit "#rrggbb", dropping any leading alpha. Returns null when there are too few digits.
        private static string? ToHexColor(string raw)
        {
            var hex = Regex.Replace(raw, "[^0-9A-Fa-f]", string.Empty);
            if (hex.Length < 6)
            {
                return null;
            }

            return "#" + hex.Substring(hex.Length - 6).ToLowerInvariant();
        }
    }
}
